rbacApiVersion: rbac.authorization.k8s.io
namespace: operator-lifecycle-manager
catalog_namespace: operator-lifecycle-manager
operator_namespace: operators
minKubeVersion: 1.11.0
imagestream: false
debug: false
olm:
  replicaCount: 1
  image:
    ref: quay.io/coreos/olm:master
    pullPolicy: Always
  service:
    internalPort: 8080
  nodeSelector:
    beta.kubernetes.io/os: linux

catalog:
  replicaCount: 1
  image:
    ref: quay.io/coreos/olm:master
    pullPolicy: Always
  service:
    internalPort: 8080
  nodeSelector:
    beta.kubernetes.io/os: linux

package:
  replicaCount: 1
  image:
    ref: quay.io/coreos/olm:master
    pullPolicy: Always
  service:
    internalPort: 5443
  nodeSelector:
    beta.kubernetes.io/os: linux

catalog_sources:
 - rh-operators
 - certified-operators
