[[constraint]]
  name = "github.com/coreos-inc/tectonic-operators"
  version = "beryllium-m1"

[[constraint]]
  name = "github.com/coreos/go-semver"
  version = "0.2.0"

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/go-openapi/spec"

[[constraint]]
  branch = "master"
  name = "github.com/go-openapi/strfmt"

[[constraint]]
  branch = "master"
  name = "github.com/go-openapi/validate"

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.0.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  branch = "release-1.9"
  name = "k8s.io/api"

[[constraint]]
  branch = "release-1.9"
  name = "k8s.io/apiextensions-apiserver"

[[constraint]]
  branch = "release-1.9"
  name = "k8s.io/apimachinery"

[[constraint]]
  branch = "release-1.9"
  name = "k8s.io/apiserver"

[[constraint]]
  name = "k8s.io/client-go"
  version = "6.0.0"
