##---
# Source: olm/templates/30_13-packageserver.yaml
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.packages.apps.redhat.com
spec:
  caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5VENDQWQyZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFjTVJvd0dBWURWUVFERXhGd1lXTnIKWVdkbExYTmxjblpsY2kxallUQWVGdzB4T0RBNU1qQXhNekU1TkROYUZ3MHlPREE1TVRjeE16RTVORE5hTUJ3eApHakFZQmdOVkJBTVRFWEJoWTJ0aFoyVXRjMlZ5ZG1WeUxXTmhNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DCkFROEFNSUlCQ2dLQ0FRRUF2RVpGRlRyaTAxSnlqcHU1L1NyaG9MYWw1dHJ3UDcvUTFIdkdQRlAyR2dlNjd6OWQKWDFkV1c4dmhQRU03Zi9Ua056eU9qNHNWTlZRWmVFSzlZa0NsZHRTSDhOcFVzcTk5cnpXMFZCeXdlRHVsRFRtVApEeWt5UFFmMXlqNHdDcXZ3WGNOWW5aeFZMNndXbFgyY2o3S2hzQzhGMmtBMlY1cFFKS21DZ01aaFBKeEVYa1hpCmNDNlhQM0lQTWkwVDN1c0pPa0JZUHdBNzJWUjF6ekdnc1JaSGFDVVJqWUVHcURndFlqcW9sdHQ5T1RXSnRNMG8KT0RmVEtKeVdMcnFabllPSXdBcDlOcGYzdjJpaHd1d28zZ0k5U2tvS1RBeng0NDhFOFB3NWF1ZkRzSzg5dmd3YwoyTVh4WldENHh2UEs4RkYrTzIrMXJyTFlKSUhVL3M3ZDlTWlF6d0lEQVFBQm8wSXdRREFPQmdOVkhROEJBZjhFCkJBTUNBcVF3SFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUYKTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQWdxMXhmVW9aK0R1RndNSkVRaC9mc0huSVdzekp5bQprTFNnWGd0blRDL3VxTWhvdUVxWktmbWRTVkdqM2l6ZXFrSVF0MDJMTDR2UkdnSk5yMXZENmFFSFQwS2ViVkluCkpZT1ZGYmNCVG9lWlBKdXpqZWZzN1lwajAzb0cvTkRUa2VaNmNPY0hvK3hUdklIOVhXaVNOQ1lsUk9FSTFPYXoKL1BTejM1V040ZlFlNWErbDYydDFSZ3F1M1lLaHhDaGNISVFvaDVlQUc5TEcxcHRXUlZFQXhhc09hVmxtMGpKVQp1SHpTYlY4cG1vL1JRUzArcDFkMllIVnFsemN1MW9aMUlIRlhzYXRGekNubkozSkVoOEFjM0VUS3pWSWRpd2FFCjljYjdNMEhpS0tmNXZyWTNIemZpWWZ3RkxxR2tIV2pnTEx5Qm5lcFh5Qi9EbDEyRGR6a2xYa2M9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
  group: packages.apps.redhat.com
  groupPriorityMinimum: 2000
  versionPriority: 15
  service:
    name: package-server
    namespace: operator-lifecycle-manager
  version: v1alpha1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: packagemanifest:system:auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: olm-operator-serviceaccount
  namespace: operator-lifecycle-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: packagemanifest-auth-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: olm-operator-serviceaccount
  namespace: operator-lifecycle-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: packagemanifest-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: olm-operator-serviceaccount
  namespace: operator-lifecycle-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: package-apiserver-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aggregated-apiserver-clusterrole
subjects:
- kind: ServiceAccount
  name: olm-operator-serviceaccount
  namespace: operator-lifecycle-manager
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: package-server-certs
  namespace: operator-lifecycle-manager
  labels:
    app: package-server
data:
  tls.crt: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURWakNDQWo2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFjTVJvd0dBWURWUVFERXhGd1lXTnIKWVdkbExYTmxjblpsY2kxallUQWVGdzB4T0RBNU1qQXhNekU1TkROYUZ3MHhPVEE1TWpBeE16RTVORE5hTUJreApGekFWQmdOVkJBTVREbkJoWTJ0aFoyVXRjMlZ5ZG1WeU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBCk1JSUJDZ0tDQVFFQTM1OWhjSjEzMUNTME5Oc0tzcW9Ic1RTaW84NGtIUUZMRjdzVm14L2pkOVo1ZXNUNEp0NkcKSFN6NTZLVVV4M1pOb09WVGV1NDA3U0t0Y2lSbXBaeEw1M2FOS0N2R2JEWlFBRk5HTTA5NlV3OVBBbmRNS3B2dApmSlpHc2lNdjRYR1JnVW16ZHZjMFZCa3JoK0hzcDhYUVhtMW0rcm1qS2pyc3JOeG9DT2FIQ2EvVDlHOG1TQkVaCkRUaDlMK1BTMDJJaHZaVmUvTTZMamhaSEdWUVRUZjRiTkNaWnVhWWhsQ293Z1ZuU3BpMWtnTkF5djZMNmdSTXQKRWhyMFNDKy9DK1dKdWxJSTJ3Mzl5N2xSTHZrVzRsWGNFUDQzdG1ZdzVkUFREWFRLOWYzL2V3WXN1SXQvV2lYUwpGRWdBRDQrU0p2aStGTzVCbGhFSEE5Wm5Hc2Y1T05OZEZRSURBUUFCbzRHbE1JR2lNQTRHQTFVZER3RUIvd1FFCkF3SUZvREFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0RBWURWUjBUQVFIL0JBSXcKQURCakJnTlZIUkVFWERCYWdpbHdZV05yWVdkbExYTmxjblpsY2k1dmNHVnlZWFJ2Y2kxc2FXWmxZM2xqYkdVdApiV0Z1WVdkbGNvSXRjR0ZqYTJGblpTMXpaWEoyWlhJdWIzQmxjbUYwYjNJdGJHbG1aV041WTJ4bExXMWhibUZuClpYSXVjM1pqTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDM2p1UGdCSHdJME85MjI5YnBkTWRVcCtkVkh3cVEKNkNER2xFekNORzlBaDJQUWtSc0hXU0xjandhMmkyeHBmbE93UUJUanRtSEs4QlFxclhMdGNibUZiV2pPU1FHSwpLWW1sS1VNdUpkZFVQSzE4WW5MSi9CYW5ySThNcHg0dkZkeHNKWFdEcUdkZzFGZXVGY0U0TGlZSUxPcFVocjY5ClF5VHFxZkNzbW1SaXNiaFVwZzliSHllUHhrQlRZZEhqQStlbis2YlkwaHk3b2xQYzZpeHZCV2lRS3JlR2k4eXEKU1RTS2xvWmtvSDhYYUs4SDFUN1NlZmpCRG43UUJYV0lMaWRTRVZ1YjJxUXdNbzdLSVYxNzc4aXBXODhseXVtZgplNEJkUUVjZU5zc01GOG41S2xZSWZKZGtPRXhzamVWc2hnMTArbFpyczZMRy80c3JBbzhvQy9KdwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
  tls.key: "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBMzU5aGNKMTMxQ1MwTk5zS3Nxb0hzVFNpbzg0a0hRRkxGN3NWbXgvamQ5WjVlc1Q0Ckp0NkdIU3o1NktVVXgzWk5vT1ZUZXU0MDdTS3RjaVJtcFp4TDUzYU5LQ3ZHYkRaUUFGTkdNMDk2VXc5UEFuZE0KS3B2dGZKWkdzaU12NFhHUmdVbXpkdmMwVkJrcmgrSHNwOFhRWG0xbStybWpLanJzck54b0NPYUhDYS9UOUc4bQpTQkVaRFRoOUwrUFMwMklodlpWZS9NNkxqaFpIR1ZRVFRmNGJOQ1padWFZaGxDb3dnVm5TcGkxa2dOQXl2Nkw2CmdSTXRFaHIwU0MrL0MrV0p1bElJMnczOXk3bFJMdmtXNGxYY0VQNDN0bVl3NWRQVERYVEs5ZjMvZXdZc3VJdC8KV2lYU0ZFZ0FENCtTSnZpK0ZPNUJsaEVIQTlabkdzZjVPTk5kRlFJREFRQUJBb0lCQUFPU2tVVHlUeExGajFkMAoxR1BzVVhra1JTRG16eTdqY1dhc3AzaTE5clZZYU5Kc1NTYWQwWGl2MmtJOE9PdkMyUlNqOVVSMmY4UDJGTjFJCjlaYlp1MkMwUlNjS0kvNWdrOENkay9hSDQ0Vm1MalgwMy9PaVVCWDRkS0t0NnpybnpKSkxNaUhKYXoyWXRWaFQKWkt0OWZvbXpwN3lEc0xhaEFGejJuSGJmNy9KWXBCNFBRUjE0ZzJWb2IrSjg0KzB5YVZ5d0FCbW1CU0hrUGNpegpjRjFOQW0wczhkakRaZlIxQk9FWjc1UmtqS0NyeDZxdG9QWlJhdkQ5dVVBYk5ISmJ3TGYyZW0xZW01MGlqamwwCnFWM0pBWGZQQWZqWG9QSlhqcEpxa28yZDZ5V0p1WENyRkVmeG12WTNNTzl1djFJRlJaaWJZUjhiUVU5ZzZVMHEKRk9uamgwRUNnWUVBN1h1aEdISER3WUpMS0k3QmdKVjRsOVFDVlJwVHcrTHM3dlExNU13VDE3WnlReVphbmFscwpPaU85K2lZUlFldnVGQjJQTndZd0NUeC9FWlAyRDR3SUhieFRUbktQOGNJL3ViMXJJS1FnTE1TWXUraTJET0pvCjhGWm9VSFlMVU5hc1JuOUV6azd4NzJBZ29QMFZja1ZaQ0lNSjFNZCs1NE5VcmNsc3NoUzd5VEVDZ1lFQThROFcKSkNlUjFqZVhNVEd4Z0c2N01LU0kwamtCanJoR0IvWGZrbFNXOC9zTG5kd1pOeTFCTGxRZVB4ME5kYWtUNnE5ego4WFhuZWtwU09zUzlsYkE2ajRQdjlsbVJuSnFyMzFPQ0JrVjBONGpyQ2VZOGlqbVRRQitwdEdia2p2MGpuN1dhCmtmeFF3cmVLSGFMUWZ3MCsrazVwL2l1aTVHdXJYbGVldmpsQm1TVUNnWUI2RktXNXhUSFdsajVBdVRJc0FhcWUKa2pRb3Y0SDBId0doelJTdmEyRi84S0JJZUx6NGM1SFpTV3B0MzRmYmxZY3IvQTRWUVM4TWNIYjUrRS96cWc2NgpDb2ZndWUvWlhmd1laWkZlbEVDZUF1cHBIcllIWlpTQWlFclRvZnNyTVZBYVpXNWZpQ0hDNW0yZmxMcWpwWmFoClU0dUlRSTJ5UWNjVUY0bXkrZ21XNFFLQmdRREFSSGcwZmhzajhWTDJPZHlKdzhncUZCSE5Hd3JTK3NkZ3NndVEKZTBlcmNpRGgyQnVFbHVQV1ArR2dGVndXN0xTbUN5cysrL3VVM3BLWHJUUkpvRFlWSWZiVFZyMTlXeUNiRDlBMQprRkFSdTNNOGdoYm5hT1M1MElkYkRIWmdWaWVEeXlWdUt3Ri9UVVVzUGlCdU5mSjFVdlhYZEphSCtoakZOcjIyCm01Um13UUtCZ0FkYzJ3dks2djZ4c2xrb0xCb1lFNEJLb3MzMCtUKzdLd3NKVHR0RnpTZG1taENYeklNaFc1VDIKTjZFODQ3UkhvQS9Xbmo2ckxCQWhCOUI4VUFwYVVBN2UzNE9CT1JYd01xNkZEbUxuRElpa0NGVHR6Nk1xYXJGRApjYkFWTHFveVBQTFVmcEpLMkJqZ20wSCtWQ3lBaWVzM1dueXR5SFlwVnlCZHQ5RURmTzZuCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg=="
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: package-server
  namespace: operator-lifecycle-manager
  labels:
    app: package-server
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: package-server
  template:
    metadata:
      labels:
        app: package-server
    spec:
      serviceAccountName: olm-operator-serviceaccount
      containers:
      - name: package-server
        command:
        - /bin/package-server
        - -v=4
        - --debug
        image: quay.io/coreos/package-server@sha256:cc18b5711fb2126329c969f077f67f41981c87f800f6b2ceae5981422c14917b
        imagePullPolicy: Always
        ports:
        - containerPort: 443
        volumeMounts:
        - name: certs
          mountPath: /apiserver.local.config/certificates
          readOnly: true
        livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: 443
        readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: 443
      volumes:
      - name: certs
        secret:
          secretName: package-server-certs
          items:
          - key: tls.crt
            path: apiserver.crt
          - key: tls.key
            path: apiserver.key
      imagePullSecrets:
        - name: coreos-pull-secret
---
apiVersion: v1
kind: Service
metadata:
  name: package-server
  namespace: operator-lifecycle-manager
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: package-server
