rbacApiVersion: rbac.authorization.k8s.io
namespace: tectonic-system
catalog_namespace: tectonic-system
alm:
  replicaCount: 1
  image:
    ref: quay.io/coreos/alm@sha256:d3c8a14835602da60011e2a7db7bdf546f7f0116fb10c11313cd9af68bfd484a
    pullPolicy: IfNotPresent
  service:
    internalPort: 8080

catalog:
  replicaCount: 1
  image:
    ref: quay.io/coreos/catalog@sha256:e0b5e4c6f1d89122780f6d98c7052b8426c3b94d35655538f562d8849bcbbc66
    pullPolicy: IfNotPresent
  service:
    internalPort: 8080
