rbacApiVersion: rbac.authorization.k8s.io
namespace: openshift-operator-lifecycle-manager
catalog_namespace: openshift-operator-lifecycle-manager
operator_namespace: openshift-operators
imagestream: true
olm:
  replicaCount: 1
  image:
    ref: quay.io/coreos/olm@sha256:1639d570809c5827810a1870763016e8c046283632d47e0b47183c82f8e515f2
    pullPolicy: IfNotPresent
  service:
    internalPort: 8080
catalog:
  replicaCount: 1
  image:
    ref: quay.io/coreos/olm@sha256:1639d570809c5827810a1870763016e8c046283632d47e0b47183c82f8e515f2
    pullPolicy: IfNotPresent
  service:
    internalPort: 8080
package:
  replicaCount: 1
  image:
    ref: quay.io/coreos/olm@sha256:1639d570809c5827810a1870763016e8c046283632d47e0b47183c82f8e515f2
    pullPolicy: Always
  service:
    internalPort: 5443
catalog_sources:
- rh-operators
- certified-operators