rbacApiVersion: rbac.authorization.k8s.io
namespace: openshift-operator-lifecycle-manager
catalog_namespace: openshift-operator-lifecycle-manager
imagestream: true
olm:
  replicaCount: 1
  image:
    ref: quay.io/coreos/olm@sha256:3f3909a6bdf6f4bf429e114832c8cfc03c731f9403b91417d5dc246ad0448772
    pullPolicy: IfNotPresent
  service:
    internalPort: 8080
catalog:
  replicaCount: 1
  image:
    ref: quay.io/coreos/olm@sha256:3f3909a6bdf6f4bf429e114832c8cfc03c731f9403b91417d5dc246ad0448772
    pullPolicy: IfNotPresent
  service:
    internalPort: 8080
package:
  replicaCount: 1
  image:
    ref: quay.io/coreos/olm@sha256:3f3909a6bdf6f4bf429e114832c8cfc03c731f9403b91417d5dc246ad0448772
    pullPolicy: Always
  service:
    internalPort: 5443
catalog_sources:
- rh-operators
- certified-operators
