rbacApiVersion: rbac.authorization.k8s.io
namespace: openshift-operator-lifecycle-manager
catalog_namespace: openshift-operator-lifecycle-manager
operator_namespace: openshift-operators
imagestream: true
writeStatusName: operator-lifecycle-manager
olm:
  replicaCount: 1
  image:
    ref: quay.io/coreos/olm@sha256:995a181839f301585a0e115c083619b6d73812c58a8444d7b13b8e407010325f
    pullPolicy: IfNotPresent
  service:
    internalPort: 8080
  nodeSelector:
    beta.kubernetes.io/os: linux
    node-role.kubernetes.io/master: ""
  tolerations:
  - operator: Exists
catalog:
  replicaCount: 1
  image:
    ref: quay.io/coreos/olm@sha256:995a181839f301585a0e115c083619b6d73812c58a8444d7b13b8e407010325f
    pullPolicy: IfNotPresent
  service:
    internalPort: 8080
  nodeSelector:
    beta.kubernetes.io/os: linux
    node-role.kubernetes.io/master: ""
  tolerations:
  - operator: Exists
package:
  replicaCount: 2
  image:
    ref: quay.io/coreos/olm@sha256:995a181839f301585a0e115c083619b6d73812c58a8444d7b13b8e407010325f
    pullPolicy: IfNotPresent
  service:
    internalPort: 5443
  nodeSelector:
    beta.kubernetes.io/os: linux
    node-role.kubernetes.io/master: ""
  tolerations:
  - operator: Exists