installType: ocp
rbacApiVersion: rbac.authorization.k8s.io
namespace: openshift-operator-lifecycle-manager
catalog_namespace: openshift-operator-lifecycle-manager
operator_namespace: openshift-operators
imagestream: true
writeStatusName: operator-lifecycle-manager
writeStatusNameCatalog: operator-lifecycle-manager-catalog
olm:
  replicaCount: 1
  image:
    ref: quay.io/operator-framework/olm@sha256:4b7dec341fc754fdd2c8784ca7d81747ebbb2b87866b9e61ebbebc8c5614cfdc
    pullPolicy: IfNotPresent
  service:
    internalPort: 8080
  nodeSelector:
    beta.kubernetes.io/os: linux
    node-role.kubernetes.io/master: ""
  tolerations:
  - operator: Exists
  tlsCertPath: /var/run/secrets/serving-cert/tls.crt
  tlsKeyPath: /var/run/secrets/serving-cert/tls.key
catalog:
  replicaCount: 1
  image:
    ref: quay.io/operator-framework/olm@sha256:4b7dec341fc754fdd2c8784ca7d81747ebbb2b87866b9e61ebbebc8c5614cfdc
    pullPolicy: IfNotPresent
  service:
    internalPort: 8080
  nodeSelector:
    beta.kubernetes.io/os: linux
    node-role.kubernetes.io/master: ""
  tolerations:
  - operator: Exists
package:
  replicaCount: 2
  image:
    ref: quay.io/operator-framework/olm@sha256:4b7dec341fc754fdd2c8784ca7d81747ebbb2b87866b9e61ebbebc8c5614cfdc
    pullPolicy: IfNotPresent
  service:
    internalPort: 5443
  nodeSelector:
    beta.kubernetes.io/os: linux
    node-role.kubernetes.io/master: ""
  tolerations:
  - operator: Exists
