---

- name: create operator-lifecycle-manager project
  oc_project:
    name: operator-lifecycle-manager
    state: present
    node_selector:
      - ""

- name: Make temp directory for manifests
  command: mktemp -d /tmp/olm-ansible-XXXXXX
  register: mktemp
  changed_when: False

- name: Copy manifests to temp directory
  copy:
    src: "{{ item }}"
    dest: "{{ mktemp.stdout }}"
  with_fileglob: files/*.yaml