kind: ConfigMap
apiVersion: v1
metadata:
  name: olm-operators
  namespace: {{ .Values.namespace }}
data:
  customResourceDefinitions: |-
  clusterServiceVersions: |-
{{- include "packageserver.clusterserviceversion" . | cat "-" | nindent 6 | replace "      - apiVersion" "    - apiVersion" }}
  packages: |- 
{{- include "packageserver.package" . | nindent 4 }}
