{{ if and .Values.installType (eq .Values.installType "ocp") }}
# keep in sync with _packageserver.clusterserviceversion.yaml
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: packageserver.v{{ .Chart.Version }}
  namespace: {{ .Values.namespace }}
spec:
  displayName: Package Server
  description: Represents an Operator package that is available from a given CatalogSource which will resolve to a ClusterServiceVersion.
  minKubeVersion: {{ .Values.minKubeVersion }}
  keywords: ['packagemanifests', 'olm', 'packages']
  maintainers:
  - name: Red Hat
    email: openshift-operators@redhat.com
  provider:
    name: Red Hat
  links:
  - name: Package Server
    url: https://github.com/operator-framework/operator-lifecycle-manager/tree/master/pkg/package-server
  installModes:
  - type: OwnNamespace
    supported: true
  - type: SingleNamespace
    supported: true
  - type: MultiNamespace
    supported: true
  - type: AllNamespaces
    supported: true
  install:
    strategy: deployment
    spec:
      clusterPermissions:
      - serviceAccountName: packageserver
        rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - operators.coreos.com
          resources:
          - catalogsources
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - packages.apps.redhat.com
          resources:
          - packagemanifests
          verbs:
          - get
          - list
      deployments:
      - name: packageserver
{{- include "packageserver.deployment-spec" . | indent 8 }}
  maturity: alpha
  version: {{ .Chart.Version }}
  apiservicedefinitions:
    owned:
    - group: operators.coreos.com
      version: v1
      kind: PackageManifest
      name: packagemanifest
      displayName: PackageManifest
      description: A PackageManifest is a resource generated from existing CatalogSources and their ConfigMaps
      deploymentName: packageserver
      containerPort: {{ .Values.package.service.internalPort }}
{{ end }}
