apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: installplans.app.coreos.com
  annotations:
    displayName: Install Plan
    description: Represents a plan to install and resolve dependencies for Cluster Services
  labels:
    tectonic-operators.coreos.com/managed-by: tectonic-x-operator
spec:
  group: app.coreos.com
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
  scope: Namespaced
  names:
    plural: installplans
    singular: installplan
    kind: InstallPlan
    listKind: InstallPlanList
  subresources:
    # status enables the status subresource.
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          description: Spec for an InstallPlan
          required:
          - clusterServiceVersionNames
          - approval
          properties:
            source:
              type: string
              description: Name of the preferred CatalogSource
            sourceNamespace:
              type: string
              description: Namespace that contains the preffered CatalogSource
            clusterServiceVersionNames:
              type: array
              description: A list of the names of the Cluster Services
              items:
                type: string
          anyOf:
            - properties:
                approval:
                  enum:
                    - Manual
                approved:
                  type: boolean
              required:
                - approved
            - properties:
                approval:
                  enum:
                    - Automatic
