{{- if ( has "ocs" .Values.catalog_sources ) }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: ocs
  namespace: {{ .Values.catalog_namespace }}
{{ $root := . }}
data:
  customResourceDefinitions: |-
{{- range $path, $bytes := .Files.Glob "catalog_resources/ocs/**.crd.yaml" }}
  {{- range $index, $line  := $root.Files.Lines $path }}
    {{- if eq $index 0 }}
{{- $line | printf "%s%s" "- " | nindent 4 }}
    {{- else }}
{{- $line | nindent 6 }}
    {{- end }}
  {{- end }}
{{- end }}
  clusterServiceVersions: |-
{{- range $path, $bytes := .Files.Glob "catalog_resources/ocs/**.clusterserviceversion.yaml" }}
  {{- range $index, $line  := $root.Files.Lines $path }}
    {{- if eq $index 0 }}
{{- $line | printf "%s%s" "- " | nindent 4 }}
    {{- else }}
{{- $line | nindent 6 }}
    {{- end }}
  {{- end }}
{{- end }}
  packages: |-
{{- range $path, $bytes := .Files.Glob "catalog_resources/ocs/**.package.yaml" }}
  {{- range $index, $line  := $root.Files.Lines $path }}
    {{- if eq $index 0 }}
{{- $line | printf "%s%s" "- " | nindent 4 }}
    {{- else }}
{{- $line | nindent 6 }}
    {{- end }}
  {{- end }}
{{- end }}
{{ end }}
