{{- if ( has "ocs" .Values.catalog_sources ) }}
#! validate-crd: ./deploy/chart/templates/05-catalogsource.crd.yaml
#! parse-kind: CatalogSource
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ocs
  namespace: {{ .Values.catalog_namespace }}
spec:
  sourceType: internal
  configMap: ocs
  displayName: Open Cloud Services
  publisher: Red Hat
{{ end }}
