{{- if ( has "upstream-components" .Values.catalog_sources ) }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: upstream-components
  namespace: {{ .Values.catalog_namespace }}
  labels:
    tectonic-operators.coreos.com/managed-by: tectonic-x-operator
{{ $root := . }}
data:
  customResourceDefinitions: |-
{{- range $path, $bytes := .Files.Glob "catalog_resources/upstream/**.crd.yaml" }}
  {{- range $index, $line  := $root.Files.Lines $path }}
    {{- if eq $index 0 }}
{{- $line | printf "%s%s" "- " | nindent 4 }}
    {{- else }}
{{- $line | nindent 6 }}
    {{- end }}
  {{- end }}
{{- end }}
  clusterServiceVersions: |-
{{- range $path, $bytes := .Files.Glob "catalog_resources/upstream/**.clusterserviceversion.yaml" }}
  {{- range $index, $line  := $root.Files.Lines $path }}
    {{- if eq $index 0 }}
{{- $line | printf "%s%s" "- " | nindent 4 }}
    {{- else }}
{{- $line | nindent 6 }}
    {{- end }}
  {{- end }}
{{- end }}
  packages: |-
{{- range $path, $bytes := .Files.Glob "catalog_resources/upstream/**.package.yaml" }}
  {{- range $index, $line  := $root.Files.Lines $path }}
    {{- if eq $index 0 }}
{{- $line | printf "%s%s" "- " | nindent 4 }}
    {{- else }}
{{- $line | nindent 6 }}
    {{- end }}
  {{- end }}
{{- end }}
{{ end }}
