{{- if ( has "upstream-components" .Values.catalog_sources ) }}
#! validate-crd: ../../deploy/chart/templates/05-catalogsource.crd.yaml
#! parse-kind: CatalogSource
apiVersion: app.coreos.com/v1alpha1
kind: CatalogSource-v1
metadata:
  name: upstream-components
  namespace: {{ .Values.catalog_namespace }}
  annotations:
    tectonic-operators.coreos.com/upgrade-strategy: 'DeleteAndRecreate'
spec:
  name: upstream-components
  sourceType: internal
  configMap: upstream-components
  displayName: OLM Upstream Components
  publisher: CoreOS, Inc.
{{ end }}
