##---
# Source: olm/templates/0000_30_14-operatorgroup.crd.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: operatorgroups.operators.coreos.com
spec:
  group: operators.coreos.com
  version: v1alpha2
  versions:
  - name: v1alpha2
    served: true
    storage: true
  names:
    plural: operatorgroups
    singular: operatorgroup
    kind: OperatorGroup
    listKind: OperatorGroupList
  scope: Namespaced
  subresources:
    # status enables the status subresource.
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            selector:
              type: object
            serviceAccountName:
              type: string
          required:
          - selector
          type: object
        status:
          properties:
            lastUpdated:
              format: date-time
              type: string
            namespaces:
              items:
                type: object
              type: array
          required:
          - namespaces
          - lastUpdated
          type: object
      required:
      - metadata
      - spec
  version: v1alpha2
