##---
# Source: olm/templates/0000_30_13-packageserver.yaml
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.packages.apps.redhat.com
spec:
  caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5VENDQWQyZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFjTVJvd0dBWURWUVFERXhGd1lXTnIKWVdkbExYTmxjblpsY2kxallUQWVGdzB4T0RFeE1UTXdNelEwTkRaYUZ3MHlPREV4TVRBd016UTBORFphTUJ3eApHakFZQmdOVkJBTVRFWEJoWTJ0aFoyVXRjMlZ5ZG1WeUxXTmhNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DCkFROEFNSUlCQ2dLQ0FRRUF4Mis1QnJpTEU5Z3p0SXRhWnZEQm5ZTk8xdkY0R04xT1o1citQN0V6L3EvNXB5YlgKT0MyYlNSQjFrSi9nN1U2d0t0dEJFRlhISG8xVjk1V2tKMnhtU1FsOFo4L0FKZ3MyVTZDU21nVWl3Y1VxekRiVwpTMXRPWWtVUStVZlRIV3J5NzFONHl5dU5vRjJFczAxd0pwSGp0L1Vhd0xaeTNDZlhHMnluaUNZL0dacTJBRDluCkRITlEyQm1jV0xVd2tna3hwSmx3amlRcFBIbHVvRjZlR1pKdTJLRmtYc0JVQlVPcmgvS0U3TDkzUVQ4aVlLL3oKbVJsbXFHcVlla2lnSzhTQnhrVWFVRS9kWEdWQXVqcmpZNjdoRGtYZ0p0QmdOeEE3VWdEUE15eXgrVGN3NXIyZgpVNXN5R1VHSWZPMXU0aTN6Mk1iZzJjZldOUllHZkJCbzBLZmtsd0lEQVFBQm8wSXdRREFPQmdOVkhROEJBZjhFCkJBTUNBcVF3SFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUYKTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQ1ZpMGFjQ3hodERHSE5BTTN5QVFNcUxOR3VLaTlTTQpteU5hUHRLRnhNeTJqanYzejJ2TXh5eVdGQzB1SmJ1U2xKOTIzSFVMNEUweHN1V2pKOXNLZnBaQjRBbkFLOWpCCnZKYjBmMDNxV3ZVb3VUZVMydE1aYklEaVNKbEJwVWFxdjdDc0svNDRuWHJuTzdHM1dSK0JWYnVCSkpJSTc0WHkKLysvd0xvOHIrZWhIYjZQaGRtZDAyOHcxM1VZYXFqcjdjOWovWnlONzl2b2xCc1g0Qk14UGZqWWpwVHZpMSszYwpqKzZaSFpxbGRBd1VtUW9xVXdFcndsdUNPVkt3d2p3VUNSdzNNdlF6Z21Ndzg0TUtJWGZ4M2o5TWpmQjlseUFXCnZDL2YrWklJRi9BZ0M3UCt3bkFKZWtmSjB3U3dPZ2M5OWFvQUZ2dWdwSHFLaE9GNVVFV2h5ZGs9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  group: packages.apps.redhat.com
  groupPriorityMinimum: 2000
  versionPriority: 15
  service:
    name: package-server
    namespace: openshift-operator-lifecycle-manager
  version: v1alpha1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: packagemanifest:system:auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: olm-operator-serviceaccount
  namespace: openshift-operator-lifecycle-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: packagemanifest-auth-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: olm-operator-serviceaccount
  namespace: openshift-operator-lifecycle-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: packagemanifest-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: olm-operator-serviceaccount
  namespace: openshift-operator-lifecycle-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: package-apiserver-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aggregated-apiserver-clusterrole
subjects:
- kind: ServiceAccount
  name: olm-operator-serviceaccount
  namespace: openshift-operator-lifecycle-manager
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: package-server-certs
  namespace: openshift-operator-lifecycle-manager
  labels:
    app: package-server
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURhakNDQWxLZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFjTVJvd0dBWURWUVFERXhGd1lXTnIKWVdkbExYTmxjblpsY2kxallUQWVGdzB4T0RFeE1UTXdNelEwTkRaYUZ3MHhPVEV4TVRNd016UTBORFphTUJreApGekFWQmdOVkJBTVREbkJoWTJ0aFoyVXRjMlZ5ZG1WeU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBCk1JSUJDZ0tDQVFFQTQ2cld4azQxb3hLS1d6Zk8vMk1jazNyUEhadW9Fa1FrN2lVbENyMXJpUmtHWFNmTnJGeGIKMUYwS0xEZmYzTUtSeWp2VTFoakMrV0JydGxJWUlNUTdGeDBvQ0VmOGc4K294U1VIL2gveTM1b2VFbEc5cVoxdgpGZk83ZW9zVlg2L0JNN0U5MVQwZXQ3NnlQaFIxQUdKK2R3LzVHeG1scVNLTTBYeWJ6ZEZoRERjUUpTSEpzSTBOCm9qTXNrRGZJV1hkSUFBY1hTRXYvM3Q3ektzUkNXNDd6bVBKWEQ2ejVnN2VPOXRLVWJ3T0ZVTlVTZ1Y2VFgzSkEKVGZnRTE1ZHBkcDl1NnlEZTFvQjdQNnFwQ04xcllSZUU2bFptTkgwUGpkZndRUUVzYVc1ZzhTOWpZMERKRENURApqbjlZZ3FOd1hxamxWYkVnZmlBSW1WTklrN3FIbXNpbjl3SURBUUFCbzRHNU1JRzJNQTRHQTFVZER3RUIvd1FFCkF3SUZvREFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0RBWURWUjBUQVFIL0JBSXcKQURCM0JnTlZIUkVFY0RCdWdqTndZV05yWVdkbExYTmxjblpsY2k1dmNHVnVjMmhwWm5RdGIzQmxjbUYwYjNJdApiR2xtWldONVkyeGxMVzFoYm1GblpYS0NOM0JoWTJ0aFoyVXRjMlZ5ZG1WeUxtOXdaVzV6YUdsbWRDMXZjR1Z5CllYUnZjaTFzYVdabFkzbGpiR1V0YldGdVlXZGxjaTV6ZG1Nd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFEazMKNTZRbm8zb043T2daVUdkQzBlOUxhOU55bUxKdm53OGZJWmhUa1Y2WDdQQXRmSzBlVVBhbVJveWZoejA5Z2lsZwpoWTF0S1kwdkpibnducCtXWkw0b2lNODhPQkdzZlkxNnV0NFZZVlp6d3dGQWYvSS9BKzhYM2daMlhZTUxqRWtICjZOVzlxNlN4NHpSOWorVjJSdjZmbFd1U0t5OVU4cGVyclpCakJHdStqRWtXQjNUQis3aVVhUVFIOXMrd3l5alIKYlJRSlo0Y3Rwb2xoS3hicUsvRzkyWmRITlZTaU5HcmNDZjRmT05KZ1BoV0FQdDJ2QmhGeXRzN1dGbFE5engxagpkMS9zZXZOM0JKN25MTFA4MXg3Y29XNTRZQndyZkg3Y2YweG1EeUhTN3dnNk42OWpDbzZTSnZCNy82QUdXcWdqCk1NdGJHSHdzbjZTRGgxZlhuNWM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBNDZyV3hrNDFveEtLV3pmTy8yTWNrM3JQSFp1b0VrUWs3aVVsQ3IxcmlSa0dYU2ZOCnJGeGIxRjBLTERmZjNNS1J5anZVMWhqQytXQnJ0bElZSU1RN0Z4MG9DRWY4Zzgrb3hTVUgvaC95MzVvZUVsRzkKcVoxdkZmTzdlb3NWWDYvQk03RTkxVDBldDc2eVBoUjFBR0orZHcvNUd4bWxxU0tNMFh5YnpkRmhERGNRSlNISgpzSTBOb2pNc2tEZklXWGRJQUFjWFNFdi8zdDd6S3NSQ1c0N3ptUEpYRDZ6NWc3ZU85dEtVYndPRlVOVVNnVjZUClgzSkFUZmdFMTVkcGRwOXU2eURlMW9CN1A2cXBDTjFyWVJlRTZsWm1OSDBQamRmd1FRRXNhVzVnOFM5alkwREoKRENURGpuOVlncU53WHFqbFZiRWdmaUFJbVZOSWs3cUhtc2luOXdJREFRQUJBb0lCQVFEY0Z6L2lIYUdFc0Z2SQpxejhWYlQ4bTQ4WnVIUmh4OENhemduMDQwTDJ3bjl5akdlT2ZDUHBOWmxSN1F0akxsZDFTNEZ4MVRTTFA2Z0szCkVzMzRmenVRc01NT25tampGRkZYcE9FQkx1bWdlR0V4M0l1NStWUjJxRlZKdGtOSGFhVWd6K3V5eFk5NG1vVzkKdGhFVitpSEFBRlVWZWNuSXBIbjEycnpVVCtHOTUzcUZ6emtZNXBON2p0aTBXZERpTWVqSkdKNC9UWGJhSVlFcQpCV3h4OG9wSVFla2ZrZmxLSU95VDgzK1FCcVBXbktSNWY0UUlGWXRMOVdsa1p3V3p1alQwYWl2WW52NkVHb0JvCnFkbkpLYjFzR1hCRUd3RmpSV3ZtMHBFY2pqOW56NDNnL1ZkelRIY0E1YlFKMkxMT2NPQ2F0d1Q5bGlXUkM3SWwKeHgzOVpscUJBb0dCQU80TXBDRWkzNm9DWUFxSGh4WnZMUm9ON1dIM3NCRVVxNWZ2U0g0ODlsZHRsTDNONEhSQgpseDFlbjZmaTNQcS9ORXQvWnZzZUdTYzNqSnFOSVNpNUhKN2FEYjZVMlp0N3ZlSWtHa3JyWEdleTJjYVQ4ejBMCnlFVmRhSnBDN0tJMXE1WW5mRjdjSFpsUFVwZ01POWNFVGMxSW8wTnlsd0RibUZOWVhuL1VBMWVSQW9HQkFQVFYKeDlWS2hkcVNuRWFoSUVLN2ZOWlpKZEVWSmQ5R2ZXWjNvVjNZU3ZLWWl4K0w0RHhJbVZoeElpNTE2d1BNdTV4dApPUE5FeU1qSkdEeWZ4RUx0WXBUcXdiS1U2UWYvYm44RmtEQTlGVEc0UGpPejgrQWZ1NGMzbFU1cWxpQlVrQ1NqCmlOWm8rQ1FBbzRMV0VYOS9CN2I2MXlOUldGNHl4bWVERFVWU1daTUhBb0dBWVVFcTRSclZWQ2pxUWdNQ3pzaVgKSFpqcERlaGF0Mi9CZHk1Y2FLN1JXZ0M4RHh1SWd4YTAvVnZHVUpuZi9GV1hzT3laRHlsSnozcmpaOVVXNGdOVwp6Uk43SUF6Q0pzTFVYZ3F2NzBIZkc4SzNOR2tIckQ0ZkVTL0xaNUxHQ0xOeXFjTHlEZk5SNkd1KzY3Mjd5T25LCk8zOWNyRmFwbU1FZXA1Wm43VU9hSmZFQ2dZQXhmUkRTaFNpL1FJbEVJWWVDMWFEck5zUFZHbUE0WEdnMmtSSFcKQlVWSStocU0rdG9OZFdOQnBFU1RmWlJPaFZDYTB0MERGekU2bktOQWhjN0c5SExMeFJQNEErK0NoVmdSWnM5NQpZSzlyQ0dIU1U1cUZBQVVJMU94aUdGdFdGNkczTmpNUG05SWtmTmlRTnJMOHdYR093KzgrblUrdVlyY0Y3MUI4ClphUGpld0tCZ1FDK0h6N0liUnJsRk0xNGdLV3dqa1RQQXVEUEVZSkJTS3g4OXpPV0hlU2NjcTBCOHo1bmV6bW0KUUFGMVQ4TlJHTXBMZkVCaVE0dGR3RWJxQ0Y3UWtEbGRValVUcEUwT0FRczdISFp2YjJ6RThLKzFrOEJSM0tzTgpoT1J5NGZKZlJOdWRRdm1RMzdtSXJncVVSZmFjNDFnQ1ZZQ2E1aUU3dVpVQzJraGtRM0dmZHc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: package-server
  namespace: openshift-operator-lifecycle-manager
  labels:
    app: package-server
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: package-server
  template:
    metadata:
      labels:
        app: package-server
    spec:
      serviceAccountName: olm-operator-serviceaccount
      containers:
      - name: package-server
        command:
        - /bin/package-server
        - -v=4
        - --secure-port=5443
        - --global-namespace
        - openshift-operator-lifecycle-manager
        image: quay.io/coreos/olm@sha256:1639d570809c5827810a1870763016e8c046283632d47e0b47183c82f8e515f2
        imagePullPolicy: Always
        ports:
        - containerPort: 5443
        volumeMounts:
        - name: certs
          mountPath: /apiserver.local.config/certificates
          readOnly: true
        livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: 5443
        readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: 5443
      volumes:
      - name: certs
        secret:
          secretName: package-server-certs
          items:
          - key: tls.crt
            path: apiserver.crt
          - key: tls.key
            path: apiserver.key
      imagePullSecrets:
        - name: coreos-pull-secret
---
apiVersion: v1
kind: Service
metadata:
  name: package-server
  namespace: openshift-operator-lifecycle-manager
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 5443
  selector:
    app: package-server
