apiVersion: app.coreos.com/v1alpha1
kind: OperatorVersion-v1
metadata:
  name: alm-operator
spec:
  version: 0.0.1
  maturity: pre-alpha
  requirements:
  - requirementType: customresourcedefinition
    resourceDefinitionLink: /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/apptypes.app.coreos.com
  - requirementType: configmap
    resourceDefinitionLink: /api/v1/namespaces/kube-system/configmaps/cluster-features
    values:
      - path: features.apiextension
        value: true
  installStrategy:
    todo: EvB
