#! validate-crd: apptype.crd.yaml
# Fields intentionally left null to test UI empty states
apiVersion: app.coreos.com/v1alpha1
kind: AppType-v1
metadata:
  namespace: default 
  name: testapp
spec:
  displayName: Test App
  keywords: ['test', 'testapp', 'example', 'coreos', 'open source']
  maintainers:
  - name: John Doe
    email: john.doe@example.com
  labels:
    alm-owner-testapp: testapp.apptypev1s.app.coreos.com.v1alpha1 
  selector:
    matchLabels:
      alm-owner-testapp: testapp.apptypev1s.app.coreos.com.v1alpha1 
