#! validate-crd: clusterserviceversion.crd.yaml
# Fields intentionally left null to test UI empty states
apiVersion: app.coreos.com/v1alpha1
kind: ClusterServiceVersion-v1
metadata:
  namespace: default 
  name: testapp
spec:
  displayName: Test App
  keywords: ['test', 'testapp', 'example', 'coreos', 'open source']
  maintainers:
  - name: John Doe
    email: john.doe@example.com
  labels:
    alm-owner-testapp: testapp.clusterserviceversionv1s.app.coreos.com.v1alpha1 
  selector:
    matchLabels:
      alm-owner-testapp: testapp.clusterserviceversionv1s.app.coreos.com.v1alpha1
  install:
    strategy: image
    spec:
      image: test
  version: 0.0.1
  maturity: alpha
  customresourcedefinitions:
    owned:
    - name: etcdclusters-v1.etcd.database.coreos.com
      displayName: Etcd Cluster
      description: Represents a cluster of etcd nodes.
      statusDescriptors:
        - path: importantMetrics
          displayName: Important Metrics
          description: Important prometheus metrics for the etcd cluster.
          x-descriptors:
            - urn:alm:descriptor:com.tectonic.ui:metrics
          value:
            queries:
            - query: has_leader
              name: Has Active Leader
              type: Gauge
              subtype: boolean
            - query: leader_changes_seen_total
              name: Leader Changes
              type: Counter
        - path: prometheus
          displayName: Prometheus Endpoint
          description: Endpoint of the prometheus instance for the etcd cluster.
          x-descriptors:
          - urn:alm:descriptor:io.prometheus:prometheus.v1
          - urn:alm:descriptor:org.w3:link
        - path: dashboard
          displayName: Dashboard
          description: URL of a Grafana dashboard for the etcd cluster.
          x-descriptors:
          - urn:alm:descriptor:com.tectonic.ui:important.link
          - urn:alm:descriptor:org.w3:link
        - path: serviceName
          displayName: Service Name
          description: The service name for the running etcd cluster.
          x-descriptors:
          - urn:alm:descriptor:com.coreos.etcd:api.v3.grpc
          - urn:alm:descriptor:com.coreos.etcd:api.v2.rest
