
apiVersion: apps/v1
kind: Deployment
metadata:
  name: packageserver
  namespace: openshift-operator-lifecycle-manager
  labels:
    app: packageserver
spec:
  strategy:
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      app: packageserver
  template:
    metadata:
      labels:
        app: packageserver
    spec:
      serviceAccountName: packageserver
      nodeSelector:
                  beta.kubernetes.io/os: linux
                  node-role.kubernetes.io/master: ""
                  
      tolerations:
                  - operator: Exists
                  
      containers:
      - name: packageserver
        command:
        - /bin/package-server
        - -v=4
        - --secure-port
        - "5443"
        - --global-namespace
        - openshift-operator-lifecycle-manager
        image: quay.io/coreos/olm@sha256:995a181839f301585a0e115c083619b6d73812c58a8444d7b13b8e407010325f
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5443
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: 5443
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: 5443

