apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-operator
  namespace: openshift-operator-lifecycle-manager
  labels:
    app: catalog-operator
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: catalog-operator
  template:
    metadata:
      labels:
        app: catalog-operator
    spec:
      serviceAccountName: olm-operator-serviceaccount
      containers:
        - name: catalog-operator
          command:
          - /bin/catalog
          args:
          - '-namespace'
          - openshift-operator-lifecycle-manager
          - -configmapServerImage=quay.io/operator-framework/configmap-operator-registry:latest
          - -writeStatusName
          - operator-lifecycle-manager-catalog
          - -tls-cert
          - /var/run/secrets/serving-cert/tls.crt
          - -tls-key
          - /var/run/secrets/serving-cert/tls.key
          image: quay.io/operator-framework/olm@sha256:4b7dec341fc754fdd2c8784ca7d81747ebbb2b87866b9e61ebbebc8c5614cfdc
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
            - containerPort: 8081
              name: metrics
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
          env:
          
          - name: RELEASE_VERSION
            value: "0.0.1-snapshot"
          
          
          volumeMounts:
          - mountPath: /var/run/secrets/serving-cert
            name: serving-cert
          
      
      volumes:
      - name: serving-cert
        secret:
          secretName: catalog-operator-serving-cert
          optional: true
      
      nodeSelector:
        beta.kubernetes.io/os: linux
        node-role.kubernetes.io/master: ""
        
      tolerations:
        - operator: Exists
        
