##---
# Source: olm/templates/30_13-packageserver.yaml
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.packages.apps.redhat.com
spec:
  caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5VENDQWQyZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFjTVJvd0dBWURWUVFERXhGd1lXTnIKWVdkbExYTmxjblpsY2kxallUQWVGdzB4T0RBNU1qQXhNekU1TkRGYUZ3MHlPREE1TVRjeE16RTVOREZhTUJ3eApHakFZQmdOVkJBTVRFWEJoWTJ0aFoyVXRjMlZ5ZG1WeUxXTmhNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DCkFROEFNSUlCQ2dLQ0FRRUFyQVp5SmczWjE2SnFtTUNuNmFMMlZJWGJPalhqeXhwMHZxaklVMkdCWlpjMjJwbmUKVWtGQXBMcnhQZWpTL0ZWVzd3SmNuTFhuZHhnZ3NNVFNXMmlLQk94UEVLTjNNLy91bndFclhGV0dMUDlPK3l3KwplM0w3ajIyWUhvWTlQUWlybHBYNDZYRThSSjgxNklyVEFFRC92UHh1dXVEbEJBZ1ZqbFFLcEZqTytCcTA4bFhPClpDZzBSYzB3TEpTWkljTzhoQk1TL1dEbHNaWGk5aEZkUmhKQi9HOGJVeGozdElpT1g3aW0vSjVDK2xXU0gyY1kKY0tQNkVsdkVwYkt1L0tVY24rbGNSNnBiazRpNzY3SWdrWlJNd3M2Y0hsZVFRbHZ4SW5pZnErSVk2b09FekcrZgpiaVN3V2poUkplTXc3ZDQwamNYU3U3aTh1R1FrVFAxaW1zYk5BUUlEQVFBQm8wSXdRREFPQmdOVkhROEJBZjhFCkJBTUNBcVF3SFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUYKTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSkVXaDVNd296eC81SnAxMzdRcGVyN2xhN3FBR2IyTgp6ME9pdys3MlpaSXlFVldwTWRUaHNpL3dYeVRvR0hKWTdIODJkWjVldGszbU9VR3doODdxNFByQmR3Z0tKV2Q4Ck42bUdLUTkvb2NjeUNZR2tuQm4xcXZDdzA1SE1CeTJNcDNEb0V3THVPOUhKZTBvUlJXTkF2dnk2eGM4Y0NKN3QKUjFxOUl2RFYxeGYzNHF2QmhGYjQreE5zNWRoaFRKNjJFelFMcXlwTG1yT1hRTGl0ZTlvKzg2Y0xsaytpYVJXSwpwRmFQT0kvUFdMYVNnZTNxVFVFWk1rVmQwRmtWdnFiNDVDZVkrYmdVNWFIWkNXRU5pRGZkOWloWmMyU2tHcERNCnE1Ymc2YnoreHFFdGdEeXhKcXJreDEwS2x0NlB3cnNIWGk5aGhwNTRvbVJseXI0SHUyZVdPaDA9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
  group: packages.apps.redhat.com
  groupPriorityMinimum: 2000
  versionPriority: 15
  service:
    name: package-server
    namespace: olm
  version: v1alpha1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: packagemanifest:system:auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: olm-operator-serviceaccount
  namespace: olm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: packagemanifest-auth-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: olm-operator-serviceaccount
  namespace: olm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: packagemanifest-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: olm-operator-serviceaccount
  namespace: olm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: package-apiserver-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aggregated-apiserver-clusterrole
subjects:
- kind: ServiceAccount
  name: olm-operator-serviceaccount
  namespace: olm
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: package-server-certs
  namespace: olm
  labels:
    app: package-server
data:
  tls.crt: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKakNDQWc2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFjTVJvd0dBWURWUVFERXhGd1lXTnIKWVdkbExYTmxjblpsY2kxallUQWVGdzB4T0RBNU1qQXhNekU1TkRGYUZ3MHhPVEE1TWpBeE16RTVOREZhTUJreApGekFWQmdOVkJBTVREbkJoWTJ0aFoyVXRjMlZ5ZG1WeU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBCk1JSUJDZ0tDQVFFQXVrMWhpWFBOMU1nRm13VmFGQ1pJQUcxeGlQLzFqd0xpZ2Ntaml3OFF1M09HREFpeGw5RmMKcitmTU5WVE9iRm5qRTNmY29YbGVZbGVhWjRIRmNZTzB4ZDI5UitvcVRIeDZwcnA0OW5HTnd3QTg5WmR4c0FYSwpvRS95UDdlbnlWdHlKT0hPWWkrczl6T1N1OUNBMEZOTWRDdDU1bUVtZjBoWWcxMllpbG9XR3F5bU12a1JrWkc0CnNpQThxenZyMVhRNTNMOXBRS29UOC9UTHlvRzVPY1FDbk12amw4RG1PMEY5U3JzcGp4RERoUFhPMDJCWjJEbGgKWnorckduTUxlSjZTWUJwRG1MdGUyVytHTG5lSDRFem1NVzh6RDRtTkpOVi9xM0g4RnNqYTlQTHVOV3c1MFF4bQpsS3dzaEFDZTlpcVg5UjBPbWtkTk9UTUxFR2IzSnFJZml3SURBUUFCbzNZd2REQU9CZ05WSFE4QkFmOEVCQU1DCkJhQXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUZCd01DTUF3R0ExVWRFd0VCL3dRQ01BQXcKTlFZRFZSMFJCQzR3TElJU2NHRmphMkZuWlMxelpYSjJaWEl1YjJ4dGdoWndZV05yWVdkbExYTmxjblpsY2k1dgpiRzB1YzNaak1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQWp4Zk9uZGl3d2pSc0NLVTNJK2Rzam9CUjRaanV0CmR4WlhpQUswUmlnLzRuYm1pR1N2c1FPUXZwTWUwQlM4S2FxaHkvYWx5UTJuUURyNXRwSDlXcHRRMWFlSlJGbHUKbXlPNHFKL0VxRTBLQVFZTzBjQjNMekc3ZlhaVVFYMXV6NFM4NWZGQ3lMUU1Yb1JPRTVvSmMzajNPSjZvL1ByUQp1bDFIVzVUUlNKRG9NRTVRcDJhYStvUVdodmZmeit3T040MlpINll2SEloY2xRWEJIa2d1cWxyMWZrOUhZdGNXCm9RSERiVDhZQlJkTk9EQjRObGlrUTNjb3JaSjR5SUxuMzZxR2lJSkhOeGdFazZBNVBHOE9lbjhlUk91UHVVMlYKdXZYbWt0WVlaV3d0Z1NZMFVEczJYS25jQlpwYVI1S0l3U1VlbU41M2wwSnplb3ZENzNWV1paSDIKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
  tls.key: "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBdWsxaGlYUE4xTWdGbXdWYUZDWklBRzF4aVAvMWp3TGlnY21qaXc4UXUzT0dEQWl4Cmw5RmNyK2ZNTlZUT2JGbmpFM2Zjb1hsZVlsZWFaNEhGY1lPMHhkMjlSK29xVEh4NnBycDQ5bkdOd3dBODlaZHgKc0FYS29FL3lQN2VueVZ0eUpPSE9ZaStzOXpPU3U5Q0EwRk5NZEN0NTVtRW1mMGhZZzEyWWlsb1dHcXltTXZrUgprWkc0c2lBOHF6dnIxWFE1M0w5cFFLb1Q4L1RMeW9HNU9jUUNuTXZqbDhEbU8wRjlTcnNwanhERGhQWE8wMkJaCjJEbGhaeityR25NTGVKNlNZQnBEbUx0ZTJXK0dMbmVINEV6bU1XOHpENG1OSk5WL3EzSDhGc2phOVBMdU5XdzUKMFF4bWxLd3NoQUNlOWlxWDlSME9ta2ROT1RNTEVHYjNKcUlmaXdJREFRQUJBb0lCQUFwT0Iyd2I3TEd0VXFvTgpkTHNTbHY3M0RzV2VLczM3UWQ0ZDhoN1orWG4wM09CRGh0YzM3R0dLZDhBbmJiZU9qVUhoYW1IQUhkbGdzUml5CmsrSkFmN3BHRnBjb3U2ZzVabXRjZXg1ZWo1SE9ySkNGRFBQSWpqbXAwbU4xM0NFR0h0MHRaRVlJRHhBcFdSOXMKWEFPcDU5dXhIKy8vUmFyYXJKS3ZsYVZwY0RtUFpPZDJUd0NXSFVuTVJ5YU9TaVRadzVrT2dFUzVBWVphYUpZQwpkYUJPQUh2WkR6dk5WMlFCOG9UZGhETUhlMVU1bmwyYkRwRjE5QlE4OU4vZGlZdi9BUnFPQVpaaG5laVZNWGtkCjhIc01FeXJsRnZPSjd1eGdMYlVnSzl5VmNhb01pbk9vc3d5TjdMQVVzcTBxYzdQZTA0TXVwNGkxNVFyTndOTGUKUGRzejBCa0NnWUVBOE9CSnF2N3Vld3BQQXJzUlFPVFIwZThjM3RyU3lMTEVVQXV2Nzc2TFlIRzZZOTlzUnF0Mgo0VTJKZG0veGhNUFFHRW5URG9UMEdiMVNuZUtMUHNrTUgraTB2NzhUMmN6M2xRUzk2QjMySmdyVTNwTFRYeDBUCkY4d2J3S3VUcW53NWRiNytMWmVneklxUXlvaGhpUzhXZmV3NHkvVWRoQmM0ZzNQOWl2bkZGaFVDZ1lFQXhmL24KRm16OUZFY3JEemx3bW5tM05SZ1NLMEdGeDd2S3B4T3p6SWpnbFp1OW1JU0daYkxkdGRsMUkweWYwZURKNzE4QwpLTUZVMlZjNkJTNGhkN0VFSTY5U0E0RkxJSnlyTlc1bzd0cnlQZisrU1cwS3dERjlNUXljL3JQSXhPR25BTkVxCnNqeFJVRStrSHgxZWVmYzBXU3RGcXBLemNWOWN5aGQvd2hiYVp4OENnWUFCYUY0bDJLMk9ISVpQcnNZd0NlWk0KQXNpNWFLLzRxa3JKYVBnVFA1clM2bmM3WkMvZXpkdTQvMW9CVGpBc0pYVE8zNGVUT3lXdUROUXh4Z1FvVHNaNgpYVUxKS0JXMm5TTUpST2pUTlhHZDBVeGpMSnA5b003ZXdidWJ5YVRvUnllU3o1WHVzRWNwU3RvRHhQNUU3ZmlFCnJkKzdHV2lkd0FEOWk2ejhwZThIN1FLQmdRQ2JELzl0VzZ1VHZ1eWsvcW9HQUg2UGNTdUJmczREanpsMVFZUFYKRWZrNGtZQ1pPbWg2cXVyaGFNMUkrTkJOTU10VTBNWkRIcTJSakxOZXJUTCtwcjRFS0dDRmFETnE5ZWRMY0Exegp5anBlZmJRTGt2OFJaM0NSQWp6TmFBVTYwekhUL1B1QUhLYmR5NUZQNE5ORmwya0MwRlc5OFNmaENQc0ZOZ1FTCi80ekpwd0tCZ0NnUk55SVZ5NjB4bW9iTXgvTm5VZXhPaHREZ1ZTOURieTc1aUZ3SGZjVERtNTBhR0RHZVZkZDAKNGxGbWFrVGJ1V2ZQZGdYMEV1WWtJZUZTVk9ZTGtHd0gxRGZkeWwva3pRZFdsTmRlS1RiS3Npa3NMcXExVVFBWQpGMWh6dUtZWjZBVHhiNWZhVlB2YjRrSEpleDRmSHhWZlFVaTh4NS94OU42eERLeDdRVnFXCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg=="
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: package-server
  namespace: olm
  labels:
    app: package-server
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: package-server
  template:
    metadata:
      labels:
        app: package-server
    spec:
      serviceAccountName: olm-operator-serviceaccount
      containers:
      - name: package-server
        command:
        - /bin/package-server
        - -v=4
        - --debug
        image: quay.io/coreos/package-server@sha256:cc18b5711fb2126329c969f077f67f41981c87f800f6b2ceae5981422c14917b
        imagePullPolicy: Always
        ports:
        - containerPort: 443
        volumeMounts:
        - name: certs
          mountPath: /apiserver.local.config/certificates
          readOnly: true
        livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: 443
        readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: 443
      volumes:
      - name: certs
        secret:
          secretName: package-server-certs
          items:
          - key: tls.crt
            path: apiserver.crt
          - key: tls.key
            path: apiserver.key
      imagePullSecrets:
        - name: coreos-pull-secret
---
apiVersion: v1
kind: Service
metadata:
  name: package-server
  namespace: olm
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: package-server
