apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: catalog-operator
  namespace: tectonic-system
  labels:
    app:  catalog-operator
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: catalog-operator
  template:
    metadata:
      labels:
        app: catalog-operator
    spec:
      serviceAccountName: alm-operator-serviceaccount
      containers:
        - name: catalog-operator
          command:
          - /bin/catalog
          - '-namespace'
          - tectonic-system
          image: quay.io/coreos/catalog@sha256:c9ad7180c8f498047c2ab4d0dd23b390debeaa5228c99d322a332ac95f3744c8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
          resources:
      imagePullSecrets:
        - name: coreos-pull-secret

