apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: installplan-v1s.app.coreos.com
  annotations:
    displayName: Install Plan
    description: Represents a plan to install and resolve dependencies for Cluster Services
  labels:
    tectonic-operators.coreos.com/managed-by: tectonic-x-operator
spec:
  group: app.coreos.com
  version: v1alpha1
  scope: Namespaced
  names:
    plural: installplan-v1s
    singular: installplan-v1
    kind: InstallPlan-v1
    listKind: InstallPlanList-v1
  validation:
    openAPIV3Schema:
      type: object
      description: Document which defines the desire and current state of an installation of a Cluster Service
      required:
      - clusterServiceVersionNames
      - approval
      properties:
        clusterServiceVersionNames:
          type: array
          description: A list of the names of the Cluster Services
          items:
            type: string
        approval:
          type: string
          enum:
          - Automatic
          - Manual
          - Update-Only # Will only apply an update if it updates existing packages only and doesn't add any new ones

# status:
#   type: object
#   required:
#   - phase
#   - catalogSources
#   properties:
#     phase:
#       type: string
#       enum:
#       - ""
#       - Planning
#       - RequiresApproval
#       - Installing
#       - Complete
#     conditions:
#       type: array
#       items:
#         type: object
#         properties:
#           type:
#             type: string
#             enum:
#             - Resolved
#             - Approved
#             - Installed
#             status:
#               type: string
#               enum:
#               - "True"
#               - "False"
#               - Unknown
#             lastUpdateTime:
#               type: string
#             lastTransitionTime:
#               type: string
#             reason:
#               type: string
#               enum:
#               - PlanUnknown
#               - DependenciesConflict
#               - InstallComponentFailed
#               - InstallCheckFailed
#             message:
#               type: string
#     catalogSources:
#       type: array
#       items:
#         type: string
#     plan:
#       type: array
#       items:
#         type: object
#         required:
#         - resolving
#         - resource
#         - status
#         properties:
#           resolving:
#             type: string
#           resource:
#             type: object
#             required:
#             - group
#             - version
#             - kind
#             - name
#             - manifest
#             properties:
#               group:
#                 type: string
#               version:
#                 type: string
#               kind:
#                 type: string
#               name:
#                 type: string
#               manifest:
#                 type: string
#           status:
#             type: string
#             enum:
#             - Unknown
#             - NotPresent
#             - Present
#             - Created
