kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: tectonic-system
  name: alm-operator-serviceaccount
  labels:
    tectonic-operators.coreos.com/managed-by: tectonic-x-operator
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: alm-operator-binding
  labels:
    tectonic-operators.coreos.com/managed-by: tectonic-x-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: alm-operator-serviceaccount
  namespace: tectonic-system
