##---
# Source: olm/templates/0000_30_13-packageserver.csv.yaml
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: packageserver.v8.0.0
  namespace: olm
spec:
  displayName: Package Server
  description: Represents an Operator package that is available from a given CatalogSource which will resolve to a ClusterServiceVersion.
  keywords: ['packagemanifests', 'olm', 'packages']
  maintainers:
  - name: Red Hat
    email: openshift-operators@redhat.com
  provider:
    name: Red Hat
  links:
  - name: Package Server
    url: https://github.com/operator-framework/operator-lifecycle-manager/tree/master/pkg/package-server
  install:
    strategy: deployment
    spec:
      deployments:
      - name: package-server
        spec:
          replicas: 1
          strategy:
            type: RollingUpdate
          selector:
            matchLabels:
              app: package-server
          template:
            metadata:
              labels:
                app: package-server
            spec:
              serviceAccountName: olm-operator-serviceaccount
              containers:
              - name: package-server
                command:
                - /bin/package-server
                - -v=4
                - --secure-port=5443
                - --global-namespace
                - olm
                image: quay.io/coreos/olm@sha256:1639d570809c5827810a1870763016e8c046283632d47e0b47183c82f8e515f2
                imagePullPolicy: Always
                ports:
                - containerPort: 5443
                livenessProbe:
                    httpGet:
                      scheme: HTTPS
                      path: /healthz
                      port: 5443
                readinessProbe:
                    httpGet:
                      scheme: HTTPS
                      path: /healthz
                      port: 5443
  maturity: alpha
  version: 8.0.0
  apiservicedefinitions:
    owned:
    - group: packages.apps.redhat.com
      version: v1alpha1
      kind: PackageManifest
      displayName: PackageManifest
      description: A PackageManifest is a resource generated from existing CatalogSources and their ConfigMaps
      deploymentName: package-server
      containerPort: 5443