##---
# Source: olm/templates/0000_30_13-packageserver.yaml
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.packages.apps.redhat.com
spec:
  caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5VENDQWQyZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFjTVJvd0dBWURWUVFERXhGd1lXTnIKWVdkbExYTmxjblpsY2kxallUQWVGdzB4T0RFeE1UTXdNelEwTkRWYUZ3MHlPREV4TVRBd016UTBORFZhTUJ3eApHakFZQmdOVkJBTVRFWEJoWTJ0aFoyVXRjMlZ5ZG1WeUxXTmhNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DCkFROEFNSUlCQ2dLQ0FRRUEwRk5iSG5oUGo3REFKZUQ0NVdpL3JSR2NyYXVtMlBLdTlIcXA0YXBoUnpLajZiOTAKZW1ENEJFaEgwekFSL1U2K2xZRnZ4bWYrQm9DaU9JU1JNUGtrQkJVaTJZeExSSlBYN0h0c01JaWpqMU9PelZZTQpHV2Q5VFhxUm9GdzFVTmdaT2ROVldwbmpNd0JjK3NJT0w5TWkyVVdwSGd3Tmwxd0FoTG5UR3RLS2RwcDdvaWQ2CjBIYWJicHMwWmpMMFQrMG5BdysvYmFnRDhZNE1HSjJsQjNsaUZobEtsbWkyeUZpNFhMcnRhelljdU5vSi9HTEMKWDdqOTFjWjJPcDV6VHZHZk1zVklMZjNqZURUeUcycGlCMlVOUnVhRlhMbUtqd2gvNkRpZ2h3YzZFM2luNXBZcgp6RExXMXVNZmdySC9ZNjZyZmZzUXM3aXZkLy9TK1l2MUd0d2xUd0lEQVFBQm8wSXdRREFPQmdOVkhROEJBZjhFCkJBTUNBcVF3SFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUYKTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSUlVUVB1Z1daQXJXTzRmTHBiUTF0NGduVEQwQ2pDcgozTk1TTTFtYWxwMWhIdlFyY3MzelMxMFV4VHVYaUc4Zyt3U3pKZWJSSmdQTktXWlJ4cUVYS0dXMkd4NlVWMC9UClBybjU1aTVXa1JuZGJxWEl3TjNxSkhHUExrV25xeDBUclh5ZXFuMXRLUlk3K2lKRU5RUXB3ZDFzWlVPdkFNWkIKWGlCNTlsNTNaMDQybDNHQzlFUzhDb3c5M3BhSitqT01MNk5ZZEdDS3M1L1ZIYjNEV2swRi92QmVLYkxPSnRWRgpMSEN1VFdVSXdRa2poSVY4dllYaitUd0pkT1RTQjVzVHFoenYzUWNzVnNtUDhWQ0JyWHNtTWh6emQra2wvdFhGCmpJTWs1QzVwNUw4L1hqSEtWcFBIdzZocm55N1dMSitmTkNyY09BZnZmSnlmTjB6ZVIxbXVWQnM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  group: packages.apps.redhat.com
  groupPriorityMinimum: 2000
  versionPriority: 15
  service:
    name: package-server
    namespace: olm
  version: v1alpha1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: packagemanifest:system:auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: olm-operator-serviceaccount
  namespace: olm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: packagemanifest-auth-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: olm-operator-serviceaccount
  namespace: olm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: packagemanifest-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: olm-operator-serviceaccount
  namespace: olm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: package-apiserver-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aggregated-apiserver-clusterrole
subjects:
- kind: ServiceAccount
  name: olm-operator-serviceaccount
  namespace: olm
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: package-server-certs
  namespace: olm
  labels:
    app: package-server
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKakNDQWc2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFjTVJvd0dBWURWUVFERXhGd1lXTnIKWVdkbExYTmxjblpsY2kxallUQWVGdzB4T0RFeE1UTXdNelEwTkRWYUZ3MHhPVEV4TVRNd016UTBORFZhTUJreApGekFWQmdOVkJBTVREbkJoWTJ0aFoyVXRjMlZ5ZG1WeU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBCk1JSUJDZ0tDQVFFQXkwUFd6UUlLTUpqeW9nRjMzOUpMR0JpVWwvNU5RRFoxTTdkd1lKSWtyMnZ6cmpmQTNMQloKQU5MVDVOSGtFdk1mZ0c3Y25zNHhud3Z4VUFHSDU1RVR5cG5sazNIVEtEb2Rhc1J3UnVjUTJUUkY4VlRWTXJhVAo2SlBkcTVQVFdOZG1zem11OHExaXN2bVpxZ1FDNzZZdVRCdjJKRGFqTEhJdmtRUGc0aUR3eWxHYjZxR3Fvak9MCnpKditiSmk1TVc5Z3d1ZnpIOTJydkw5ejF2TlVoUGQ5d0FZV2hsYVZoRTlOODZlSGt1SS9pZWYyVUY0VjlKTVMKSCtabnVWN1pvdXl6QXd6NjY3ajkxM1FqQ05zN245Qkg5dEVPTnVHaHhLNzJVS3Nvb2VETlJqZ0xIU0lvdW1oKwpJT3VBWXhtK1V2USsvOUxuTWQ3VVo1MzdVNWhSYnhqUUNRSURBUUFCbzNZd2REQU9CZ05WSFE4QkFmOEVCQU1DCkJhQXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUZCd01DTUF3R0ExVWRFd0VCL3dRQ01BQXcKTlFZRFZSMFJCQzR3TElJU2NHRmphMkZuWlMxelpYSjJaWEl1YjJ4dGdoWndZV05yWVdkbExYTmxjblpsY2k1dgpiRzB1YzNaak1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQS8yUjlnOEVzb2o0Sm9HZWU3YlYwYzBsSkRLVnM4CmdXRjk4SnFpM3NBTjNxV09kQkRwaUFZeEdsbFNZQWFQNkxqb3Zab01ZTThpY0g2OXQvK0gxZUpJWm5iekdoM28KaFZYVFUveFR3ajl2OVB3K2swZnNDcnlpNG9KZGVQTXhOUGdGWTJhWVM1cEExN0ExVUROc1BSUXk0Umx0YWNJaApXQzlYbzF6dEhPcWY2NkxTczdSbVBKWW5KWU1TYzN0RVJqQ2RJUFVBMERRZnl6VEZXZlRCdWdsbXhoek1veHRYCjlPU1pVck1EQ2ZibTlzZGZYYkNDaHFhWDFZZHZidW5SaEtXTmM1VEpuNGFzUnIvcW9tSkVRMzJ4MHEvS1lHbkcKSEVXTjhkSG8yWXlDeURCdWEzL2NFUVhqVUMzUUN5SlJ2R2pjTk1oeVE0ejFuOE9UanE3QW5lbFMKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBeTBQV3pRSUtNSmp5b2dGMzM5SkxHQmlVbC81TlFEWjFNN2R3WUpJa3IydnpyamZBCjNMQlpBTkxUNU5Ia0V2TWZnRzdjbnM0eG53dnhVQUdINTVFVHlwbmxrM0hUS0RvZGFzUndSdWNRMlRSRjhWVFYKTXJhVDZKUGRxNVBUV05kbXN6bXU4cTFpc3ZtWnFnUUM3Nll1VEJ2MkpEYWpMSEl2a1FQZzRpRHd5bEdiNnFHcQpvak9Mekp2K2JKaTVNVzlnd3Vmekg5MnJ2TDl6MXZOVWhQZDl3QVlXaGxhVmhFOU44NmVIa3VJL2llZjJVRjRWCjlKTVNIK1pudVY3Wm91eXpBd3o2NjdqOTEzUWpDTnM3bjlCSDl0RU9OdUdoeEs3MlVLc29vZUROUmpnTEhTSW8KdW1oK0lPdUFZeG0rVXZRKy85TG5NZDdVWjUzN1U1aFJieGpRQ1FJREFRQUJBb0lCQUJiNTVCM29UUjZSSzF3RQpybmd1WFM2c0dKL1Zyd1hESWh4bWI5MTZwNHJzdU83SWZwUnptcHZ0T09aMGswTlJHQTU4ZVpPNTJ3SVBaNGVUCnBMa1lQUlI1c09tcHhDU1g3UnRVZVJ5S29lenJhN3lMeWsyaE5iYmtmL29WQzU3UE9seW4rSTZWNnNJd1ZKNVQKTmNIQkZ4cWpUbjlwYmFob2Y5ZjBpRWNIVWpDTU5XeDc1V3hiNSszWE1lbFlDTThISmwwdlFnMXp1ZnNVdHp5bQpwVHpQelZWUUQ2ci9yemhqNUY2TklWN1EzanNRcncrNlhnNW44WklKRGdidjVOSXVqNDdIa2tkTjUvN1cxclBzCi9LTFh4WWFMSXA2SEJzU0NxZWZDSlg0WVVuWVdqbmN1S3NSWUtZSFRnb0wvK2prNDI2c3B2V3pYUGoxWDJ3U08KaVhUcFVBRUNnWUVBNm9VaTY5ZnBZT29oSHRiUW9kNEhkUE5pSjYwdHZ0MC9hbDgrcEw0SnlObDYrMzdDOXVVTQp5eDBKalAwaVJnTXlkODBYaE9ZVmhtVGtzQWpDL1o5b0JaS28zRjk0Y3pqY3QvUVd1RVIvUm5UckdvUjhtSUdaCmdXd1lJMEw3U0VNV21EamFWZzh1V0M0N1VITnZLQ0tvcmhLYm5JNktIcGppWnlPbWJGd2FqZUVDZ1lFQTNlSGIKQkN3Y0lKaHJabnBZVStjSkw2dGppbEZRQTVWMFdIekJWcU5lSnAvY05rc09BNGJTN3lBYVl6bmpkcUF1TzVpRApkc1F4UG9mRmNwTmdTb1p4USt5TS81K1pDRDVzcHZvWnBJbWI2Y3BPc0hYTEpJSlgzSHNhbEpGSmsvN3kyTFRZCm5wdWs3MnJHSjJyaGE5bGhnNFNIS3VUM2IvdE82eDU1YllaMDl5a0NnWUVBMEpSNDZxbXR0N1NFb0prT0Zla1QKV01EZW04czYxSGFTNEZpMXJuQVc0N3dKMVlSNGduNVZVcEVRM1lTRjV4OFEwOXhrL3A1a3BwTTFraHM0MGJubApHby9GLzdvcHR0RHIvZS9xQlJsbTJaTkRSdUp1cm5VVndqWVJnY3NoRXJRWWRHcWNSYzVhdWJMa3Jqajh0QVdmCllMTE1GQUh5ZGlRanVQZk1ITFFPS2dFQ2dZQkhNd0I2MkVTMldQS3QwYmlpUTlMNHp3Q0VGQStlOXNoODFKdWQKMTVLUXhsOTl0SnZzbWNqNkhzMFk1aXlObGx6L2xyTW8yMUFLQnJ0ZlJ0ZHhVcTdwNHZCajNxeldybUZqTzRJYgpBR1Zkb2lPYUVGSjlocTMyL0RITlZzbkxpZFlYb0FDYTlNcjZZTUx4UnlUSzNOaWp3VlUyZUg3R0dsaDZyaTY4CjdKWi84UUtCZ1FEZXllM1drYTViS1JBNXZtWmVkZ0Nabm1pc3BsYUhZdEMyV2lDTVJnVmtkb3gxdGJUZlUycEMKTGVLK1gwSksrTjAweEVwZFUvUXQ2S1NXMGlHUFZ0NDVma01WNWV5VXZUVERRaVdETFdtMFFGaWMxeDNGeEdQdwpFajZSMnpENUFRSUtqSVljOTRPYmF6L0xTU3JMSy9pTExRNzJTRU9MTHVwckRHb2U3RVdnNVE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: package-server
  namespace: olm
  labels:
    app: package-server
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: package-server
  template:
    metadata:
      labels:
        app: package-server
    spec:
      serviceAccountName: olm-operator-serviceaccount
      containers:
      - name: package-server
        command:
        - /bin/package-server
        - -v=4
        - --secure-port=5443
        - --global-namespace
        - olm
        image: quay.io/coreos/olm@sha256:1639d570809c5827810a1870763016e8c046283632d47e0b47183c82f8e515f2
        imagePullPolicy: Always
        ports:
        - containerPort: 5443
        volumeMounts:
        - name: certs
          mountPath: /apiserver.local.config/certificates
          readOnly: true
        livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: 5443
        readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: 5443
      volumes:
      - name: certs
        secret:
          secretName: package-server-certs
          items:
          - key: tls.crt
            path: apiserver.crt
          - key: tls.key
            path: apiserver.key
      imagePullSecrets:
        - name: coreos-pull-secret
---
apiVersion: v1
kind: Service
metadata:
  name: package-server
  namespace: olm
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 5443
  selector:
    app: package-server
