apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: alertmanagers.monitoring.coreos.com
  labels:
    alm-status-descriptors: prometheusoperator.0.13.0
    alm-owner-prometheus: prometheusoperator.0.13.0
    operated-by: prometheusoperator.0.12.0
spec:
  group: monitoring.coreos.com
  version: v1
  scope: Namespaced
  names:
    plural: alertmanagers
    singular: alertmanager
    kind: AlertManager
    listKind: AlertManagerList
