apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: default
  labels:
    prometheus: prometheus
spec:
  replicas: 2
  version: v1.5.2
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: frontend
  alerting:
    alertmanagers:
    - namespace: default
      name: alertmanager
      port: web
  resources:
    requests:
      memory: 400Mi
outputs: 
  prometheus-important-metrics: '{
    "metrics": [
      {
        "query": "has_leader", 
        "name": "Prometheus Status", 
        "type": "Status", 
        "subtype": "boolean"
      },
      {
        "query": "leader_changes_seen_total", 
        "name": "CPU Usage", 
        "type": "Gauge"
      },
      {
        "query": "leader_changes_seen_total", 
        "name": "Memory Usage", 
        "type": "Gauge"
      },
      {
        "query": "leader_changes_seen_total", 
        "name": "Filesystem Usage", 
        "type": "Gauge"
      }
    ], 
    "endpoint": "https://prometheus-prometheus"
  }'