apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata: 
  name: prometheuses.monitoring.coreos.com
  labels:
    alm-owner-prometheus: prometheus.clusterserviceversionv1s.app.coreos.com.v1alpha1
    operated-by: prometheusoperator.0.12.0
spec:
  group: monitoring.coreos.com
  version: v1
  scope: Namespaced
  names: 
    plural: prometheuses
    singular: prometheus
    kind: Prometheus
    listKind: PrometheusList
