#! validate-crd: clusterserviceversion.crd.yaml
apiVersion: app.coreos.com/v1alpha1
kind: ClusterServiceVersion-v1
metadata:
  namespace: default 
  name: prometheusoperator.0.13.0
  labels:
    alm-owner-prometheus: prometheus.apptypev1s.app.coreos.com.v1alpha1
spec:
  displayName: Prometheus
  description: An open-source monitoring system with a dimensional data model, flexible query language, efficient time series database and modern alerting approach.

  keywords: ['prometheus', 'monitoring', 'tsdb', 'alerting']

  maintainers:
  - name: Frederic Branczyk
    email: frederic.branczyk@coreos.com
  - name: Fabian Reinartz
    email: fabian.reinartz@coreos.com

  provider:
    name: CoreOS, Inc

  links:
  - name: Prometheus
    url: https://www.prometheus.io/

  labels:
    alm-owner-prometheus: prometheus.apptypev1s.app.coreos.com.v1alpha1
    alm-catalog: Open Cloud Services
    operated-by: prometheusoperator.0.12.0

  selector:
    matchLabels:
      alm-owner-prometheus: prometheus.apptypev1s.app.coreos.com.v1alpha1
      operated-by: prometheusoperator.0.12.0

  icon:
  - base64data: PHN2ZyB3aWR0aD0iMjQ5MCIgaGVpZ2h0PSIyNTAwIiB2aWV3Qm94PSIwIDAgMjU2IDI1NyIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiBwcmVzZXJ2ZUFzcGVjdFJhdGlvPSJ4TWlkWU1pZCI+PHBhdGggZD0iTTEyOC4wMDEuNjY3QzU3LjMxMS42NjcgMCA1Ny45NzEgMCAxMjguNjY0YzAgNzAuNjkgNTcuMzExIDEyNy45OTggMTI4LjAwMSAxMjcuOTk4UzI1NiAxOTkuMzU0IDI1NiAxMjguNjY0QzI1NiA1Ny45NyAxOTguNjg5LjY2NyAxMjguMDAxLjY2N3ptMCAyMzkuNTZjLTIwLjExMiAwLTM2LjQxOS0xMy40MzUtMzYuNDE5LTMwLjAwNGg3Mi44MzhjMCAxNi41NjYtMTYuMzA2IDMwLjAwNC0zNi40MTkgMzAuMDA0em02MC4xNTMtMzkuOTRINjcuODQyVjE3OC40N2gxMjAuMzE0djIxLjgxNmgtLjAwMnptLS40MzItMzMuMDQ1SDY4LjE4NWMtLjM5OC0uNDU4LS44MDQtLjkxLTEuMTg4LTEuMzc1LTEyLjMxNS0xNC45NTQtMTUuMjE2LTIyLjc2LTE4LjAzMi0zMC43MTYtLjA0OC0uMjYyIDE0LjkzMyAzLjA2IDI1LjU1NiA1LjQ1IDAgMCA1LjQ2NiAxLjI2NSAxMy40NTggMi43MjItNy42NzMtOC45OTQtMTIuMjMtMjAuNDI4LTEyLjIzLTMyLjExNiAwLTI1LjY1OCAxOS42OC00OC4wNzkgMTIuNTgtNjYuMjAxIDYuOTEuNTYyIDE0LjMgMTQuNTgzIDE0LjggMzYuNTA1IDcuMzQ2LTEwLjE1MiAxMC40Mi0yOC42OSAxMC40Mi00MC4wNTYgMC0xMS43NjkgNy43NTUtMjUuNDQgMTUuNTEyLTI1LjkwNy02LjkxNSAxMS4zOTYgMS43OSAyMS4xNjUgOS41MyA0NS40IDIuOTAyIDkuMTAzIDIuNTMyIDI0LjQyMyA0Ljc3MiAzNC4xMzguNzQ0LTIwLjE3OCA0LjIxMy00OS42MiAxNy4wMTQtNTkuNzg0LTUuNjQ3IDEyLjguODM2IDI4LjgxOCA1LjI3IDM2LjUxOCA3LjE1NCAxMi40MjQgMTEuNDkgMjEuODM2IDExLjQ5IDM5LjYzOCAwIDExLjkzNi00LjQwNyAyMy4xNzMtMTEuODQgMzEuOTU4IDguNDUyLTEuNTg2IDE0LjI4OS0zLjAxNiAxNC4yODktMy4wMTZsMjcuNDUtNS4zNTVjLjAwMi0uMDAyLTMuOTg3IDE2LjQwMS0xOS4zMTQgMzIuMTk3eiIgZmlsbD0iI0RBNEUzMSIvPjwvc3ZnPg==
    mediatype: image/svg+xml

  install:
    strategy: deployment
    spec:
      deployments:
      - replicas: 1
        template:
          metadata:
            labels:
              name: prometheus-operator
          spec:
            containers:
            - name: prometheus-operator
              image: quay.io/coreos/prometheus-operator:0.13.0
  version: 0.13.0
  maturity: beta
  replaces: prometheusoperator.0.12.0
  requirements:
  - kind: CustomResourceDefinition
    apiVersion: v1beta1
    name: prometheuses.monitoring.coreos.com
  - kind: CustomResourceDefinition
    apiVersion: v1beta1
    name: servicemonitors.monitoring.coreos.com
  - kind: CustomResourceDefinition
    apiVersion: v1beta1
    name: alertmanagers.monitoring.coreos.com
  - kind: ServiceAccount
    apiVersion: v1
    name: prometheus-operator
    rules:
    - apiGroups:
      - extensions
      resources:
      - thirdpartyresources
      verbs:
      - "*"
    - apiGroups:
      - apiextensions.k8s.io
      resources:
      - customresourcedefinitions
      verbs:
      - "*"
    - apiGroups:
      - monitoring.coreos.com
      resources:
      - alertmanagers
      - prometheuses
      - servicemonitors
      verbs:
      - "*"
    - apiGroups:
      - apps
      resources:
      - statefulsets
      verbs: ["*"]
    - apiGroups: [""]
      resources:
      - configmaps
      - secrets
      verbs: ["*"]
    - apiGroups: [""]
      resources:
      - pods
      verbs: ["list", "delete"]
    - apiGroups: [""]
      resources:
      - services
      - endpoints
      verbs: ["get", "create", "update"]
    - apiGroups: [""]
      resources:
      - nodes
      verbs: ["list", "watch"]
    - apiGroups: [""]
      resources:
      - namespaces
      verbs: ["list"]

