alm:
  replicaCount: 1
  image:
    ref: quay.io/coreos/alm:local
    pullPolicy: IfNotPresent
  service:
    internalPort: 8080

catalog:
  replicaCount: 1
  image:
    ref: quay.io/coreos/catalog:local
    pullPolicy: IfNotPresent
  service:
    internalPort: 8080

e2e:
  image:
    ref: quay.io/coreos/alm-e2e:local

job_name: e2e
