##---
# Source: olm/templates/13-catalog-operator.deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: catalog-operator
  namespace: operator-lifecycle-manager
  labels:
    app: catalog-operator
    tectonic-operators.coreos.com/managed-by: tectonic-x-operator
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: catalog-operator
  template:
    metadata:
      labels:
        app: catalog-operator
    spec:
      serviceAccountName: alm-operator-serviceaccount
      containers:
        - name: catalog-operator
          command:
          - /bin/catalog
          - '-namespace'
          - operator-lifecycle-manager
          - '-debug'
          image: quay.io/coreos/catalog@sha256:299a9cd6b34c9ccb601d6fffa8b6a633658165510940ed8c5481ce6acdad46b1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
      imagePullSecrets:
        - name: coreos-pull-secret
