apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: prometheuses.monitoring.alm.coreos.com
spec:
  group: monitoring.alm.coreos.com
  version: v1
  scope: Namespaced
  names:
    plural: prometheuses
    singular: prometheus
    kind: Prometheus
    listKind: PrometheusList