#! validate-crd: clusterserviceversion.crd.yaml
apiVersion: clusterserviceversion-v1s.app.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  namespace: staging-environment
  name: etcd-operator
  uid: bbbbbbbb-bbbb-cccc-dddd-eeeeeeeeeeee
  labels:
    alm-owner-etcd: etcd.apptypev1s.app.coreos.com.v1alpha1 
  ownerReferences:
  - apiVersion: app.coreos.com/v1alpha1
    kind: AppType-v1
    name: etcd
    uid: cccccccc-bbbb-cccc-dddd-eeeeeeeeeeee
spec:
  install:
    strategy: deployment
    spec:
      deployments:
        - replicas: 1
          template:
            metadata:
              labels:
                name: etcd-operator
            spec:
              containers:
              - name: etcd-operator
                image: quay.io/coreos/etcd-operator:v0.5.1
  version: 0.5.1
  replaces: etcdoperator.v0.5.0  
  maturity: beta
  selector:
    matchLabels:
      operated-by: etcdoperator.v0.5.1
  labels:
    operated-by: etcdoperator.v0.5.1
  requirements:
  - kind: CustomResourceDefinition
    apiVersion: v1beta1
    name: etcdclusters-v1.etcd.database.coreos.com
  - kind: ServiceAccount
    apiVersion: v1
    name: etcd-operator
    rules:
    - apiGroups:
      - etcd.database.coreos.com
      resources:
      - etcdclusters
      verbs:
      - "*"
    - apiGroups:
      - apiextensions.k8s.io
      resources:
      - customresourcedefinitions
      verbs:
      - "*"
    - apiGroups:
      - storage.k8s.io
      resources:
      - storageclasses
      verbs:
      - "*"
    - apiGroups:
      - ""
      resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      verbs:
      - "*"
    - apiGroups:
      - apps
      resources:
      - deployments
      verbs:
      - "*"
status:
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2017-08-30T13:51:53Z'
      lastTransitionTime: '2017-08-30T13:51:53Z'
      reason: OperatorRunningAndHealthy
      message: Operator is running and healthy
