#! validate-crd: installplan.crd.yaml
apiVersion: app.coreos.com/v1alpha1
kind: InstallPlan-v1
metadata:
  namespace: staging-environment
  name: etcd-operator-v1
spec:
  clusterServiceVersionNames:
  - etcd-operator-v1
  approval: Automatic
status:
  phase: Complete
  message: cool story bro
  reason: InstallCompleted
  lastUpdateTime: '2017-08-30T13:51:53Z'
  lastTransitionTime: '2017-08-30T13:51:53Z'
  conditions:
  - phase: Complete
    message: cool story bro
    reason: InstallCompleted
    lastUpdateTime: '2017-08-30T13:51:53Z'
    lastTransitionTime: '2017-08-30T13:51:53Z'
  plan:
  - resolving: etcd-operator-v1
    status: Created
    resource:
      group: apiextensions.k8s.io
      version: v1beta1
      kind: CustomResourceDefinition
      name: EtcdCluster
      manifest: |
        apiVersion: apiextensions.k8s.io/v1beta1
        kind: CustomResourceDefinition
        metadata:
          name: etcdclusters.etcd.database.coreos.com
          uid: 11111111-bbbb-cccc-dddd-eeeeeeeeeeee
          ownerReferences:
            - apiVersion: app.coreos.com/v1alpha1
              kind: ClusterServiceVersion-v1
              name: etcd
              uid: cccccccc-bbbb-cccc-dddd-eeeeeeeeeeee
          labels:
            alm-owner-etcd: etcd.clusterserviceversion-v1s.app.coreos.com.v1alpha1
          annotations:
            displayName: Etcd Cluster
            description: Represents a cluster of etc nodes as one unit.
            outputs: '{
              "etcd-cluster-service-name": {
                "displayName":"Service Name",
                "description":"The service name for the running etcd cluster.",
                "x-descriptors":["urn:alm:descriptor:com.coreos.etcd:api.v3.grpc","urn:alm:descriptor:com.coreos.etcd:api.v2.rest"]
              },
              "etcd-dashboard": {
                "displayName":"Dashboard",
                "description":"URL of a Grafana dashboard for the etcd cluster.",
                "x-descriptors":["urn:alm:descriptor:com.tectonic.ui:important.link","urn:alm:descriptor:org.w3:link"]
              },
              "etcd-prometheus": {
                "displayName":"Prometheus Endpoint",
                "description":"Endpoint of the prometheus instance for the etcd cluster.",
                "x-descriptors":["urn:alm:descriptor:io.prometheus:prometheus.v1","urn:alm:descriptor:org.w3:link"]
              },
              "etcd-important-metrics": {
                "displayName":"Important Metrics",
                "description":"Important prometheus metrics for the etcd cluster.",
                "x-descriptors":["urn:alm:descriptor:com.tectonic.ui:metrics"]
              }}'
        spec:
          group: etcd.database.coreos.com
          version: v1alpha1
          scope: Namespaced
          validation:
            openAPIv3:
              type: object
              description: Represents a single instance of etcd
              additionalProperties: false
              required:
              - version
              properties:
                version:
                  type: string
                  description: Version string
                  pattern: ^(0|[1-9]d*).(0|[1-9]d*).(0|[1-9]d*)(-(0|[1-9]d*|d*[a-zA-Z-][0-9a-zA-Z-]*)(.(0|[1-9]d*|d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(+[0-9a-zA-Z-]+(.[0-9a-zA-Z-]+)*)?$
                size:
                  type: number
                  description: The size of the etcd cluster
                  min: 1
                  max: 9
                labels:
                  type: object
                  description: labels to apply to associated objects
          names:
            plural: etcdclusters
            singular: etcdcluster
            kind: EtcdCluster
            listKind: EtcdClusterList
