#! validate-crd: operatorversion.crd.yaml
apiVersion: app.coreos.com/v1alpha1
kind: OperatorVersion
metadata:
  namespace: staging-environment
  name: etcd-operator
  uid: bbbbbbbb-bbbb-cccc-dddd-eeeeeeeeeeee
  ownerReferences:
  - apiVersion: app.coreos.com/v1alpha1
    kind: AppType-v1
    name: etcd
    uid: cccccccc-bbbb-cccc-dddd-eeeeeeeeeeee
spec:
  installStrategy:
    type: image
    image: quay.io/coreos/etcd-operator:v0.5.1
  version: 0.5.1
  replaces: 0.5.0
  maturity: beta
  selector:
    matchLabels:
      operated-by: etcd-operator
  requirements:
  - kind: CustomResourceDefinition
    apiVersion: v1beta1
    name: etcdclusters-v1.etcd.database.coreos.com
  - kind: ServiceAccount
    apiVersion: v1
    name: etcd-operator
    namespace: kube-system
    rules:
    - apiGroups:
      - etcd.database.coreos.com
      resources:
      - etcdclusters
      verbs:
      - "*"
    - apiGroups:
      - apiextensions.k8s.io
      resources:
      - customresourcedefinitions
      verbs:
      - "*"
    - apiGroups:
      - storage.k8s.io
      resources:
      - storageclasses
      verbs:
      - "*"
    - apiGroups:
      - ""
      resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      verbs:
      - "*"
    - apiGroups:
      - apps
      resources:
      - deployments
      verbs:
      - "*"
status:
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2017-08-30T13:51:53Z'
      lastTransitionTime: '2017-08-30T13:51:53Z'
      reason: OperatorRunningAndHealthy
      message: Operator is running and healthy
