#! validate-crd: samples/etcd/resolved/etcdcluster.crd.yaml
apiVersion: database.coreos.com/v1alpha1
kind: EtcdCluster
metadata:
  namespace: default
  name: my-etcd-cluster
  ownerReferences:
    - apiVersion: app.coreos.com/v1alpha1
      kind: ClusterServiceVersion
      name: etcd-operator
      uid: bbbbbbbb-bbbb-cccc-dddd-eeeeeeeeeeee
  labels:
    operated-by: etcdoperator.v0.5.1
    alm-owner-etcd: etcd.apptypev1s.app.coreos.com.v1alpha1
    alm-owner-vault: vault.apptypev1s.app.coreos.com.v1alpha1
spec:
  labels:
    alm-owner-etcd: etcd.apptypev1s.app.coreos.com.v1alpha1 
  version: 0.5.1
  size: 3
outputs:
  etcd-cluster-service-name: my-etcd-cluster
  etcd-dashboard: https://internal-grafana/dashboards/my-etcd-cluster
  etcd-backup-count: 23
  etcd-last-backup: '2009-06-15T13:45:30'
  etcd-first-backup: '2009-06-15T13:45:29'
  etcd-active-connections: 1001 
  etcd-prometheus: https://my-etcd-cluster-prometheus
  etcd-important-metrics: "{\"metrics\": [{\"query\": \"has_leader\", \"name\": \"Has Active Leader\", \"type\": \"Gauge\", \"subtype\": \"boolean\"},{\"query\": \"leader_changes_seen_total\", \"name\": \"Leader Changes\", \"type\": \"Counter\"}], \"endpoint\": \"https://my-etcd-cluster-prometheus\"}"
status:
  observedGeneration: 1
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2017-08-30T13:51:53Z'
      lastTransitionTime: '2017-08-30T13:51:53Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
      
