installType: upstream
rbacApiVersion: rbac.authorization.k8s.io
namespace: olm
catalog_namespace: olm
operator_namespace: operators
imagestream: false
writeStatusName: '""'
writePackageServerStatusName: ""
olm:
  replicaCount: 1
  image:
    ref: quay.io/operator-framework/olm@sha256:2c389d2e380c842cbf542820ad4493249164302ddf0e699b0a37105d234e67ee
    pullPolicy: IfNotPresent
  service:
    internalPort: 8080
catalog:
  replicaCount: 1
  image:
    ref: quay.io/operator-framework/olm@sha256:2c389d2e380c842cbf542820ad4493249164302ddf0e699b0a37105d234e67ee
    pullPolicy: IfNotPresent
  service:
    internalPort: 8080
package:
  replicaCount: 2
  image:
    ref: quay.io/operator-framework/olm@sha256:2c389d2e380c842cbf542820ad4493249164302ddf0e699b0a37105d234e67ee
    pullPolicy: Always
  service:
    internalPort: 5443
  securityContext:
    runAsUser: 1000
catalog_sources:
- rh-operators
