rbacApiVersion: rbac.authorization.k8s.io
namespace: kube-system
catalog_namespace: kube-system
alm:
  replicaCount: 1
  image:
    ref: quay.io/coreos/olm@sha256:00b6b703d235b622d8e2e5424d0bfb4aa9e46ec10abd295def47e2c6ed7a18e8
    pullPolicy: IfNotPresent
  service:
    internalPort: 8080
catalog:
  replicaCount: 1
  image:
    ref: quay.io/coreos/catalog@sha256:08667c7c409c8ca044c05db9bf90a0aa9954ce511490e72df4a3493cebd58b8e
    pullPolicy: IfNotPresent
  service:
    internalPort: 8080
catalog_sources:
- ocs
