rbacApiVersion: rbac.authorization.k8s.io
namespace: olm
catalog_namespace: olm
operator_namespace: operators
imagestream: false
writeStatusName: '""'
olm:
  replicaCount: 1
  image:
    ref: quay.io/openshift/origin-operator-lifecycle-manager:latest
    pullPolicy: IfNotPresent
  service:
    internalPort: 8080
catalog:
  replicaCount: 1
  image:
    ref: quay.io/openshift/origin-operator-lifecycle-manager:latest
    pullPolicy: IfNotPresent
  service:
    internalPort: 8080
package:
  replicaCount: 2
  image:
    ref: quay.io/openshift/origin-operator-lifecycle-manager:latest
    pullPolicy: Always
  service:
    internalPort: 5443
catalog_sources:
- rh-operators
