rbacApiVersion: rbac.authorization.k8s.io
namespace: olm
catalog_namespace: olm
operator_namespace: operators
imagestream: false
olm:
  replicaCount: 1
  image:
    ref: quay.io/coreos/olm@sha256:995a181839f301585a0e115c083619b6d73812c58a8444d7b13b8e407010325f
    pullPolicy: IfNotPresent
  service:
    internalPort: 8080
catalog:
  replicaCount: 1
  image:
    ref: quay.io/coreos/olm@sha256:995a181839f301585a0e115c083619b6d73812c58a8444d7b13b8e407010325f
    pullPolicy: IfNotPresent
  service:
    internalPort: 8080
package:
  replicaCount: 1
  image:
    ref: quay.io/coreos/olm@sha256:995a181839f301585a0e115c083619b6d73812c58a8444d7b13b8e407010325f
    pullPolicy: Always
  service:
    internalPort: 5443
catalog_sources:
- rh-operators