apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: subscription-v1s.app.coreos.com
  annotations:
    displayName: Subscription
    description: Subcribes service catalog to a source and channel to recieve updates for packages.
  labels:
    tectonic-operators.coreos.com/managed-by: tectonic-x-operator
spec:
  group: app.coreos.com
  version: v1alpha1
  scope: Namespaced
  names:
    plural: subscription-v1s
    singular: subscription-v1
    kind: Subscription-v1
    listKind: SubscriptionList-v1
  validation:
    openAPIV3Schema:
      type: object
      description: Represents a subscription to a source and channel
      required:
      - source
      - apptype
      - channel
      - approval
      properties:
        source:
          type: string
          description: Name of a CatalogSource that defines where and how to find the channel

        apptype:
          type: string
          description: Name of the AppType that this subscription tracks

        channel:
          type: string
          description: Name of the channel to track

        approval:
          type: string
          description: Approval setting determines behavior when a new version is available.
          enum:
          - Automatic
          - Update-Only # Will only apply an update if it updates existing packages only and doesn't add any new ones
          - Manual
