#! validate-crd: operatorversion.crd.yaml
apiVersion: app.coreos.com/v1alpha1
kind: OperatorVersion-v1
metadata:
  name: alm-operator
spec:
  version: 0.0.1
  maturity: pre-alpha
  replaces: 0.0.0
  requirements:
  - kind: CustomResourceDefinition 
    apiVersion: v1beta1
    name: apptypes.app.coreos.com
    namespace: my-namespace
    sha256: a916282c05b74d39076e223ebde312f6de2346f1fbb87c75bb315cad9cc6eab7
  - kind: ConfigMap
    apiVersion: v1
    name: cluster-features
    namespace: kube-system
    matchExpressions:
      - {key: features.apiextension, operator: In, values: [true]}
  - kind: ServiceAccount
    apiVersion: v1
    name: alm-service
    namespace: kube-system
    rules:
    # This is a list of permissions that are required for the operator compenent (using the above serviceAccount)
    # to do its job. A user with appropriate permissions will need to create it (automated in tectonic UI) 
    - apiGroups: [""]
      resources: ["pods"]
      verbs: ["get", "list", "watch"]
    - apiGroups: ["batch", "extensions"]
      resources: ["jobs"]
      verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
    - apiGroups: [""]
      resources: ["configmaps"]
      resourceNames: ["my-config"]
      verbs: ["get"]
  - kind: ServiceAccount
    apiVersion: v1
    name: alm-cluster-aware-service
    namespace: kube-system
    optional: true
    rules:
    - apiGroups: [""]
      resources: ["configmaps"]
      resourceNames: ["cluster-features"]
      verbs: ["get"]
  installStrategy:
    todo: EvB