#! validate-crd: clusterserviceversion.crd.yaml
apiVersion: app.coreos.com/v1alpha1
kind: ClusterServiceVersion-v1
metadata:
  name: alm-operator.0.0.1
  namespace: alm
spec:
  displayName: ALM
  description: ALM manages the Open Cloud Services in your cluster.
  keywords: ['ALM', 'operator', 'coreos', 'coreos']
  maintainers:
  - name: CoreOS
    email: team-apps@coreos.com
  provider:
    name: CoreOS, Inc
  labels:
    alm-owner-etcd: alm.clusterserviceversionv1s.app.coreos.com.v1alpha1
    alm-catalog: Open Cloud Services
    operated-by: alm-operator.0.0.1
  selector:
    matchLabels:
      alm-owner-etcd: alm.clusterserviceversionv1s.app.coreos.com.v1alpha1
      operated-by: alm-operator.0.0.1
  links:
  - name: Blog
    url: https://coreos.com/alm
  version: 0.0.1
  maturity: pre-alpha
  labels:
    alm-owner-alm: almoperator.app.coreos.com.0.0.1
  selector:
    matchLabels:
      alm-owner-alm: almoperator.app.coreos.com.0.0.1
    matchExpressions:
    - {key: alm-status, operator: In, values: [running, pending, stopped]}
  customresourcedefinitions:
    owned:
    - clusterserviceversion-v1s.app.coreos.com
  install:
    strategy: deployment
    spec:
      deployments:
        - replicas: 1
          template:
            metadata:
              labels:
                name: alm-operator
            spec:
              containers:
              - name: alm-operator
                image: quay.io/coreos/alm-operator:v0.0.1
