apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: installplan-v1s.app.coreos.com
  annotations:
    displayName: Install Plan
    description: Represents a plan to install and resolve dependencies for Cloud Services
spec:
  group: app.coreos.com
  version: v1alpha1
  scope: Namespaced
  validation:
    openAPIV3Schema:
      type: object
      description: Document which defines the desire and current state of an installation of a Cloud Service
      required:
      - desiredClusterServiceVersions
      properties:
        desiredCloudServiceVersions:
          type: array
          description: A list of the names of the Cloud Services
          items:
            type: string

# Schema for status key written by the operator:
#status:
# type: object
# required:
# - status
# properties:
#   status:
#     type: string
#     enum:
#     - Pending
#     - Complete
#   plan:
#     type: array
#     items:
#       type: object
#       required:
#       - resolving
#       - resource
#       properties:
#         resolving:
#           type: string
#         resource:
#           type: object
#           required:
#           - group
#           - version
#           - kind
#           - name
#           - status
#           - manifest
#           properties:
#             group:
#               type: string
#             version:
#               type: string
#             kind:
#               type: string
#             name:
#               type: string
#             status:
#               type: string
#               enum:
#               - Not Present
#               - Present
#               - Created
#             manifest:
#               type: string

  names:
    plural: installplan-v1s
    singular: installplan-v1
    kind: InstallPlan-v1
    listKind: InstallPlanList-v1
