---
# Source: olm/templates/0000_50_olm_00-namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-operator-lifecycle-manager
  
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-operators
  
