apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata: 
  name: apptype-v1s.app.coreos.com
  annotations:
    displayName: App Type
    description: Represents an App Type that has been registered with ALM.
spec: 
  group: app.coreos.com
  version: v1alpha1
  scope: Namespaced
  validation:
    openAPIV3Schema:
      type: object
      description: Document which defines how to model an App as a CRD in an ALM compatible way
      required:
      - displayName
      - labels
      - selector
      properties:
        displayName:
          type: string
          description: Human readable name of the application that will be displayed in the ALM UI

        description:
          type: string
          description: Human readable description of what the application does

        # Open question: do these belong as k8s annotations? Should ALM do that?
        keywords:
          type: array
          description: List of keywords which will be used to discover and categorize app types
          items:
            type: string

        # Open question: do these belong as k8s annotations? Should ALM do that?
        maintainers:
          type: array
          description: Those responsible for the creation of this specific app type
          items:
            type: object
            description: Information for a single maintainer
            required:
            - name
            - email
            properties:
              name:
                type: string
                description: Maintainer's name
              email:
                type: string
                description: Maintainer's email address
                format: email
            optionalProperties:
              type: string
              description: "Any additional key-value metadata you wish to expose about the maintainer, e.g. github: <username>"

        links:
          type: array
          description: Interesting links to find more information about the project, such as marketing page, documentation, or github page
          items:
            type: object
            description: A single link to describe one aspect of the project
            required:
            - name
            - url
            properties:
              name:
                type: string
                description: Name of the link type, e.g. homepage or github url
              url:
                type: string
                description: URL to which the link should point
                format: uri

        icon:
          type: array
          description: Icon which should be rendered with the application information
          required:
          - base64data
          - mediatype
          properties:
            base64data:
              type: string
              description: Base64 binary representation of the icon image
              pattern: ^(?:[A-Za-z0-9+/]{4}){0,16250}(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$
            mediatype:
              type: string
              description: Mediatype for the binary data specified in the base64data property
              enum:
              - image/gif
              - image/jpeg
              - image/png
              - image/svg+xml
        labels:
          type: object
          description: Labels that will be applies to associated resources
        selector:
          type: object
          description: Label selector to find resources associated with this AppType
          properties:
            matchLabels:
              type: object
              description: Label key:value pairs to match directly
            matchExpressions:
              type: array
              descriptions: A set of expressions to match against the resource.
              items:
                allOf:
                  - type: object
                    required:
                    - key
                    - operator
                    - values
                    properties:
                      key:
                        type: string
                        description: the key to match
                      operator:
                        type: string
                        description: the operator for the expression
                        enum: 
                        - In
                        - NotIn
                        - Exists
                        - DoesNotExist
                      values:
                        type: array
                        description: set of values for the expression 

  names: 
    plural: apptype-v1s
    singular: apptype-v1
    kind: AppType-v1
    listKind: AppTypeList-v1
