kind: ConfigMap
apiVersion: v1
metadata:
  name: alm-config
  namespace: {{ .Values.namespace }}
data:
  alm.config.file: |-
    almOperator:
      interval: 15m
      namespaces:
        - {{ .Values.namespace }}