apiVersion: rbac.authorization.k8s.io/v1beta1
# Need ClusterRole to access customresourcedefintions
kind: ClusterRole
metadata:
  name: alm-operator
rules:
- apiGroups:
  - app.coreos.com
  resources:
  - operatorversion-v1s
  - apptype-v1
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - "*"
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.namespace }}-alm-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: {{ template "fullname" . }}-serviceaccount
  namespace: {{ .Values.namespace }}