apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: elasticsearches.logging.openshift.io
spec:
  group: logging.openshift.io
  names:
    kind: Elasticsearch
    listKind: ElasticsearchList
    plural: elasticsearches
    singular: elasticsearch
  scope: Namespaced
  version: v1alpha1
  validation:
    openAPIV3Schema:
      properties:
        spec:
          description: Specification of the desired behavior of the Elasticsearch cluster
          properties:
            nodes:
              description: Specification of the different Elasticsearch nodes
              properties:
                roles:
                  description: The specific Elasticsearch cluster roles the node should perform
                  type: object
                replicas:
                  description: Number of nodes to deploy
                  format: int32
                  type: integer
                spec:
                  description: Specification of the Elasticsearch node
                  properties:
                    image:
                      description: The image to use for the Elasticsearch node
                      type: string
                    resources:
                      description: The resource requirements for the Elasticsearch node
                      properties:
                        limits:
                          description: 'Limits describes the maximum amount of compute
                            resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                          type: object
                        requests:
                          description: 'Requests describes the minimum amount of compute
                            resources required. If Requests is omitted for a container,
                            it defaults to Limits if that is explicitly specified, otherwise
                            to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                          type: object
                nodeSelector:
                  description: Define which Nodes the Pods are scheduled on.
                  type: object
                storage:
                  description: The type of backing storage that should be used for the node
                  properties:
                    hostPath:
                      description: Use host node storage
                      type: object
                    emptyDir:
                      description: Use ephemeral storage
                      type: object
                    volumeClaimTemplate:
                      description: 'Volume claims that act similarly to the VolumeClaimTemplates
                        field of StatefulSets. A number of PVCs will be generated based on the number of
                        node replicas'
                      type: object
                    persistentVolumeClaim:
                      description: Use a specifically named Persistent Volume Claim
                      type: object
            nodeSpec:
              description: Specification to be applied to all the Elasticsearch nodes
              properties:
                image:
                  description: The image to use for the Elasticsearch nodes
                  type: string
                resources:
                  description: The resource requirements for the Elasticsearch nodes
                  properties:
                    limits:
                      description: 'Limits describes the maximum amount of compute
                        resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                      type: object
                    requests:
                      description: 'Requests describes the minimum amount of compute
                        resources required. If Requests is omitted for a container,
                        it defaults to Limits if that is explicitly specified, otherwise
                        to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                      type: object
            serviceAccountName:
              description: The service account for the Elasticsearch nodes in this cluster
              type: string
            configMapName:
              description: The configmap for the Elasticsearch nodes in this cluster
              type: string
            secretName:
              description: The secret for the Elasticsearch nodes in this cluster
              type: string
