namespace: alm
catalog-namespace: tectonic-system
alm:
  replicaCount: 1
  image:
    ref: quay.io/coreos/alm:master
    pullPolicy: Always
  service:
    internalPort: 8080

catalog:
  replicaCount: 1
  image:
    ref: quay.io/coreos/catalog:master
    pullPolicy: Always
  service:
    internalPort: 8080
