apiVersion: batch/v1
kind: Job
metadata:
  name: e2e
  namespace: {{ .Values.namespace }}
spec:
  template:
    metadata:
      name: e2e
    spec:
      containers:
      - name: e2e
        image:  {{ .Values.e2e.image.ref }}
        command: ["./e2e/e2e.sh"]
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      restartPolicy: Never
  backoffLimit: 1
