apiVersion: operatorversion-v1s.app.coreos.com/v1alpha1
kind: OperatorVersion
metadata:
  namespace: staging-environment
  name: etcd-operator
spec:
  installStrategy:
    type: image
    image: quay.io/coreos/etcd-operator:v0.5.1
  version: 0.5.1
  replaces: 0.5.0
  maturity: beta
  requirements:
  - kind: EtcdCluster-v1  
    apiVersion: v1beta1
    name: etcdcluster.etcd.database.coreos.com
  - kind: ServiceAccount
    apiVersion: v1
    name: etcd-operator
    namespace: kube-system
    blocksInstall: true
    rules:
    - apiGroups:
      - etcd.database.coreos.com
      resources:
      - etcdclusters
      verbs:
      - "*"
    - apiGroups:
      - apiextensions.k8s.io
      resources:
      - customresourcedefinitions
      verbs:
      - "*"
    - apiGroups:
      - storage.k8s.io
      resources:
      - storageclasses
      verbs:
      - "*"
    - apiGroups: 
      - ""
      resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      verbs:
      - "*"
    - apiGroups:
      - apps
      resources:
      - deployments
      verbs:
      - "*"