#! validate-crd: operatorversion.crd.yaml
apiVersion: app.coreos.com/v1alpha1
kind: OperatorVersion-v1
metadata:
  namespace: default
  name: etcdoperator.v0.5.1
  labels:
    alm-owner-etcd: etcd.apptypev1s.app.coreos.com.v1alpha1 
spec:
  install:
    strategy: deployment
    spec:
      deployments:
        - replicas: 1
          template:
            metadata:
              name: etcd-operator-alm-owned
              labels:
                name: etcd-operator-alm-owned
            spec:
              containers:
              - name: etcd-operator
                image: quay.io/coreos/etcd-operator:v0.5.1
                env:
                - name: MY_POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: MY_POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
  version: 0.5.1
  replaces: etcdoperator.v0.5.0
  maturity: beta
  labels:
    operated-by: etcdoperator.v0.5.1
  selector:
    matchLabels:
      operated-by: etcdoperator.v0.5.1
  requirements:
  - kind: CustomResourceDefinition
    apiVersion: v1beta1
    name: etcdclusters-v1.etcd.database.coreos.com
  - kind: ServiceAccount
    apiVersion: v1
    name: etcd-operator
    rules:
    - apiGroups:
      - etcd.database.coreos.com
      resources:
      - etcdclusters
      verbs:
      - "*"
    - apiGroups:
      - apiextensions.k8s.io
      resources:
      - customresourcedefinitions
      verbs:
      - "*"
    - apiGroups:
      - storage.k8s.io
      resources:
      - storageclasses
      verbs:
      - "*"
    - apiGroups: 
      - ""
      resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      verbs:
      - "*"
    - apiGroups:
      - apps
      resources:
      - deployments
      verbs:
      - "*"
