apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata: 
  name: etcdclusters-v1.etcd.database.coreos.com
  labels:
    alm-owner-etcd: etcd.clusterserviceversionv1s.app.coreos.com.v1alpha1
spec:
  group: etcd.database.coreos.com
  version: v1beta2
  scope: Namespaced
  validation:
    openAPIv3:
      type: object
      description: Represents a single instance of etcd
      additionalProperties: false
      required:
      - version
      properties:
        version:
          type: string
          description: Version string
          pattern: ^(0|[1-9]d*).(0|[1-9]d*).(0|[1-9]d*)(-(0|[1-9]d*|d*[a-zA-Z-][0-9a-zA-Z-]*)(.(0|[1-9]d*|d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(+[0-9a-zA-Z-]+(.[0-9a-zA-Z-]+)*)?$
          x-alm-capabilities:
          - urn:alm:capability:versioning:semver
        size:
          type: number
          description: The size of the etcd cluster
          min: 1
          max: 9
          x-alm-capabilities:
          - urn:alm:capability:pod:count
          - urn:alm:capability:number:integer
        labels:
          type: object
          description: labels to apply to associated objects
  names:
    plural: etcdclusters-v1
    singular: etcdcluster-v1
    kind: EtcdCluster-v1
    listKind: EtcdClusterList-v1
