apiVersion: v1
kind: Secret
metadata:
  name: coreos-pull-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJZMjl5Wlc5eksyRnNiVjlsTW1VNlVsZElNVVpXUVRFd01qQlhSVVV5VGxsU1RFSk5WMUpCTlRsV1VqSkdVRGxOTmtOUFVGUlBWRUpNTlZaYVRrUTRUVWd3TkZKT1R6ZFdNelJET0VneFFnPT0iLAogICAgICAiZW1haWwiOiAiIgogICAgfQogIH0KfQ==
type: kubernetes.io/dockerconfigjson