rbacApiVersion: authorization.openshift.io
namespace: local
watchedNamespaces: local
catalog_namespace: local
alm:
  replicaCount: 1
  image:
    ref: quay.io/coreos/olm:local
    pullPolicy: IfNotPresent
  service:
    internalPort: 8080

catalog:
  replicaCount: 1
  image:
    ref: quay.io/coreos/catalog:local
    pullPolicy: IfNotPresent
  service:
    internalPort: 8080

packageserver:
  replicaCount: 1
  image:
    ref: quay.io/coreos/package-server:local
    pullPolicy: Always
  service:
    internalPort: 443

catalog_sources:
 - rh-operators
