installType: upstream
rbacApiVersion: rbac.authorization.k8s.io
namespace: local
writeStatusName: '""'
catalog_namespace: local
operator_namespace: local-operators
debug: true

olm:
  replicaCount: 1
  image:
    ref: quay.io/operator-framework/olm:local
    pullPolicy: IfNotPresent
  service:
    internalPort: 8080

catalog:
  replicaCount: 1
  image:
    ref: quay.io/operator-framework/olm:local
    pullPolicy: IfNotPresent
  service:
    internalPort: 8080

package:
  replicaCount: 1
  image:
    ref: quay.io/operator-framework/olm:local
    pullPolicy: IfNotPresent
  service:
    internalPort: 5443
  tolerations:
    - operator: Exists

catalog_sources:
  - rh-operators
