apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: alm-operator
  namespace: tectonic-system
  labels:
    app:  alm-operator
    tectonic-operators.coreos.com/managed-by: tectonic-x-operator
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: alm-operator
  template:
    metadata:
      labels:
        app:  alm-operator
    spec:
      serviceAccountName: alm-operator-serviceaccount
      containers:
        - name: alm-operator
          command:
          - /bin/alm
          image: quay.io/coreos/alm@sha256:39f528957d69a5449e4f83126785de73db0452f4da16007531b1867b93c6238b
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
          env:
          - name: OPERATOR_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: OPERATOR_NAME
            value: alm-operator
      imagePullSecrets:
        - name: coreos-pull-secret
