#! validate-crd: operatorversion.crd.yaml
apiVersion: app.coreos.com/v1alpha1
kind: OperatorVersion-v1
metadata:
  namespace: alm-vault-example
  name: vault-operator.0.0.2
  labels:
    alm-owner-vault: vault.apptypev1s.app.coreos.com.v1alpha1 
spec:
  install:
    strategy: deployment
    spec:
      deployments:
      - replicas: 1
        template:
          metadata:
            labels:
              name: vault-operator
          spec:
            containers:
            - name: vault-operator
              image: quay.io/coreos/vault-operator:0.0.2
  version: 0.0.2
  maturity: beta
  replaces: vaultoperator.0.0.1
  labels:
    operated-by: vaultoperator.0.0.2
  selector:
    matchLabels:
      operated-by: vaultoperator.0.0.2
  requirements:
  - kind: CustomResourceDefinition
    apiVersion: v1beta1
    name: etcdclusters-v1.etcd.database.coreos.com
  - kind: CustomResourceDefinition
    apiVersion: v1alpha1
    name: vaultclusters-v1.vault.security.coreos.com
  - kind: ServiceAccount
    apiVersion: v1
    name: etcd-operator
    namespace: kube-system
    rules:
    - apiGroups:
      - etcd.database.coreos.com
      resources:
      - etcdclusters
      verbs:
      - "*"
    - apiGroups:
      - vault.security.coreos.com
      resources:
      - vaultclusters
      verbs:
      - "*"
    - apiGroups:
      - storage.k8s.io
      resources:
      - storageclasses
      verbs:
      - "*"
    - apiGroups: 
      - ""
      resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      verbs:
      - "*"
    - apiGroups:
      - apps
      resources:
      - deployments
      verbs:
      - "*"
