apiVersion: app.coreos.com/v1alpha1
kind: OperatorVersion
metadata:
  namespace: staging-environment
  name: vault-operator
spec:
  installStrategy:
    type: image
    image: quay.io/coreos/vault-operator:0.0.2
  version: 0.0.2
  maturity: beta
  replaces: 0.0.1
  requirements:
  - kind: CustomResourceDefinition
    apiVersion: v1beta1
    name: etcdclusters-v1.etcd.database.coreos.com
  - kind: CustomResourceDefinition
    apiVersion: v1alpha1
    name: vaultclusters-v1.vault.security.coreos.com
  - kind: ServiceAccount
    apiVersion: v1
    name: etcd-operator
    namespace: kube-system
    rules:
    - apiGroups:
      - etcd.database.coreos.com
      resources:
      - etcdclusters
      verbs:
      - "*"
    - apiGroups:
      - vault.security.coreos.com
      resources:
      - vaultclusters
      verbs:
      - "*"
    - apiGroups:
      - storage.k8s.io
      resources:
      - storageclasses
      verbs:
      - "*"
    - apiGroups: 
      - ""
      resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      verbs:
      - "*"
    - apiGroups:
      - apps
      resources:
      - deployments
      verbs:
      - "*"
