apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata: 
  name: vaultservice.vault.security.coreos.com
spec: 
  group: vault.security.coreos.com
  version: v1alpha1
  scope: Namespaced
  validation:
    openAPIv3:
      type: object
      description: Represents a single instance of Vault
      additionalProperties: false
      required:
      - version
      properties:
        version:
          type: string
          description: Version string
          pattern: ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$
        nodes:
          type: number
          description: The number of nodes in the Vault cluster
          min: 1
          max: 9

  outputs:
  # The name of the cluster, based on the service name. Filled in by the vault-operator.
  #
  # Sample output: `my-vault-cluster`
  - name: vault-service-name
    description: The service name for the running vault cluster.
    x-alm-capabilities:
    - urn:alm:capability:io.vaultproject:api.v1

  names: 
    plural: vaultservices
    singular: vaultservice
    kind: VaultService
